import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {hash} from '../engine/scenario.js';import {saveRun} from '../engine/runner.js';import {dimensions,validateReview} from '../engine/semantic.js';
import {createContinuationContract,createContinuationRun,runContinuation,reviewContinuation,evaluateContinuation,continuationReviewInput,continuationJudgeHash,continuationReviewVersion} from '../engine/continuation.js';
import {createContinuationPlan,executeContinuation,summarizeContinuation,validateContinuationCalibration,verifyContinuationPlan} from '../engine/continuation-experiment.js';
import {continuationReferences,continuationActions} from '../engine/continuation-fixtures.js';
const parent=JSON.parse(await readFile(new URL('../evidence/diagnostic-rerun/report.json',import.meta.url),'utf8'));
const temp=()=>mkdtemp(path.join(tmpdir(),'taskwright-continuation-'));
function fake(run,kind='supported',inputs=[]){let i=0;const actions=continuationActions(run.continuation.mode,run.continuation.history,kind);return async()=>({metadata:{cliVersion:parent.plan.controls.cliVersion,requestedModel:run.continuation.contract.configuration.model,reasoningEffort:'low',protocolVersion:'json-actions-2'},diagnostics:[],next:async input=>{inputs.push(structuredClone(input));return structuredClone(actions[i++]);},close(){}});}
async function setup(){const c=createContinuationContract(parent),dir=await temp(),calibration=[];for(const ref of continuationReferences){const p=c.parents.find(p=>p.mode===ref.mode&&p.trial===1),run=createContinuationRun(c,p.runId,ref.history,'replay');await runContinuation(run,dir,null,{adapterFactory:fake(run,ref.kind)});calibration.push(run);}return {...createContinuationPlan(c,calibration,parent.plan.controls.cliVersion),dir};}
function review(run,reference){const input=continuationReviewInput(run),raw={criteria:Object.keys(dimensions).map(id=>({id,outcome:reference?.targets[id]||'pass',claim:input.reply.slice(0,20),reason:'Controlled review plumbing fixture.',evidence:[{source_id:'ticket',quote:input.evidence.ticket.slice(0,20)}]}))};return {id:randomUUID(),createdAt:new Date().toISOString(),runId:run.id,originalHash:hash(run),inputHash:hash(input),version:continuationReviewVersion,judgeHash:continuationJudgeHash,status:'completed',raw,evaluation:validateReview(raw,input),execution:{cliVersion:parent.plan.controls.cliVersion,requestedModel:run.continuation.contract.configuration.model,reasoningEffort:'low',protocolVersion:continuationReviewVersion,continuationContractHash:run.continuation.contract.hash},executionDiagnostics:[]};}
test('continuation preserves original conversation, supplies the new answer and scopes tools to the current turn',async()=>{const c=createContinuationContract(parent),p=c.parents[0],run=createContinuationRun(c,p.runId,'failed'),before=hash(parent),inputs=[];await runContinuation(run,await temp(),null,{adapterFactory:fake(run,'supported',inputs)});assert.equal(inputs[0].conversation.length,3);assert.equal(inputs[0].conversation[1].content,p.reply);assert.equal(inputs[0].priorTurnTrace.length,p.trace.length);assert.equal(inputs[0].trace.length,0);assert.match(inputs[0].instructions,/do not ask again/);assert.equal(run.trace.filter(e=>e.tool==='record_escalation'&&e.ok).length,1);assert.equal(hash(parent),before);assert.equal(evaluateContinuation(run).criteria.find(c=>c.id==='handoff').outcome,'pass');});
test('all four authority and history cells implement their action boundary',async()=>{const c=createContinuationContract(parent);for(const mode of ['execute','prepare'])for(const history of ['untried','failed']){const p=c.parents.find(p=>p.mode===mode),run=createContinuationRun(c,p.runId,history);await runContinuation(run,await temp(),null,{adapterFactory:fake(run)});assert.ok(run.evaluation.criteria.filter(c=>c.id!=='writing').every(c=>c.outcome==='pass'));assert.equal(run.trace.filter(e=>e.tool==='record_escalation'&&e.ok).length,mode==='execute'&&history==='failed'?1:0);}});
test('prior retrieval never substitutes for current required reads; duplicate handoffs fail',async()=>{const c=createContinuationContract(parent),run=createContinuationRun(c,c.parents[0].runId,'failed');await runContinuation(run,await temp(),null,{adapterFactory:fake(run)});const changed=structuredClone(run);changed.trace=changed.trace.filter(e=>e.tool!=='read_document');assert.equal(evaluateContinuation(changed).criteria.find(c=>c.id==='sources').outcome,'fail');const duplicate=structuredClone(run);duplicate.trace.push(structuredClone(run.trace.find(e=>e.tool==='record_escalation'&&e.ok)));assert.equal(evaluateContinuation(duplicate).criteria.find(c=>c.id==='handoff').outcome,'fail');});
test('calibration fixtures have declared structural outcomes and references are frozen before execution',async()=>{const {plan,runs}=await setup();verifyContinuationPlan(plan,runs);for(const {reference,run} of plan.calibration)assert.equal(run.evaluation.criteria.filter(c=>c.id!=='writing').every(c=>c.outcome==='pass')?'pass':'fail',reference.task);assert.equal(runs.length,12);assert.equal(new Set(runs.map(r=>r.id)).size,12);assert.equal(plan.contract.parentReportHash,hash(parent));assert.throws(()=>verifyContinuationPlan(plan,runs.map((r,i)=>i? r:{...r,mode:'replay'})));});
test('complete batch retains all first outcomes, with no retry after an errored slot',async()=>{const {plan,runs,dir}=await setup(),evidence=await temp();let calls=0,reviews=0;const original=structuredClone(runs),result=await executeContinuation(plan,runs,dir,evidence,{cliVersion:plan.cliVersion,runSupport:async(r,d)=>{calls++;if(calls===1){r.status='error';r.error='Scripted error';r.evaluation=evaluateContinuation(r);await saveRun(d,r);}else await runContinuation(r,d,null,{adapterFactory:fake(r)});},review:async r=>{reviews++;const reference=plan.calibration.find(c=>c.run.id===r.id)?.reference;return review(r,reference);}});assert.equal(calls,12);assert.equal(reviews,23);assert.equal(result.decision,'incomplete');assert.equal(result.rows.filter(r=>r.outcome==='pass').length,11);await assert.rejects(executeContinuation(plan,original,dir,evidence,{cliVersion:plan.cliVersion}));});
test('calibration false pass blocks every support slot while preserving the twelve reference reviews',async()=>{const {plan,runs,dir}=await setup();let supportCalls=0,reviewCalls=0;const result=await executeContinuation(plan,runs,dir,await temp(),{cliVersion:plan.cliVersion,runSupport:()=>supportCalls++,review:async r=>{reviewCalls++;return review(r);}});assert.equal(supportCalls,0);assert.equal(reviewCalls,12);assert.equal(result.decision,'blocked');assert.ok(result.rows.every(r=>r.run.status==='blocked'));assert.equal(validateContinuationCalibration(plan,result.calibration),false);});
test('cancelling before calibration records cancelled reviews and support slots without creating an adapter',async()=>{const {plan,runs,dir}=await setup(),controller=new AbortController();controller.abort();let adapters=0,support=0;const result=await executeContinuation(plan,runs,dir,await temp(),{cliVersion:plan.cliVersion,signal:controller.signal,runSupport:()=>support++,review:(r,options)=>reviewContinuation(r,{...options,adapterFactory:()=>{adapters++;throw Error('Must not start');}})});assert.equal(adapters,0);assert.equal(support,0);assert.equal(result.calibration.results.length,12);assert.ok(result.calibration.results.every(r=>r.review.status==='cancelled'));assert.ok(result.rows.every(r=>r.run.status==='cancelled'));});
test('matching grades cannot excuse changed conversation or invalid quote provenance',async()=>{const {plan,runs,dir}=await setup(),result=await executeContinuation(plan,runs,dir,await temp(),{cliVersion:plan.cliVersion,runSupport:(r,d)=>runContinuation(r,d,null,{adapterFactory:fake(r)}),review:async r=>review(r,plan.calibration.find(c=>c.run.id===r.id)?.reference)});assert.equal(result.decision,'continuation_passed');const changed=structuredClone(result.rows);changed[0].run.continuation.conversation[2].content='A different answer';changed[0].review=review(changed[0].run);assert.equal(summarizeContinuation(plan,changed,result.calibration).decision,'blocked');const calibration=structuredClone(result.calibration);calibration.results[0].review.raw.criteria[0].evidence[0].quote='Nonexistent quotation';const {hash:ignored,...value}=calibration;calibration.hash=hash(value);assert.equal(validateContinuationCalibration(plan,calibration),false);});
