import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {hash} from '../engine/scenario.js';
import {baseline} from '../engine/configurations.js';
import {validateAction,readRun} from '../engine/runner.js';
import {diagnosticAdapter,diagnosticBounds} from '../engine/diagnostic-adapter.js';
import {diagnosticSupportPrompt} from '../engine/diagnostic-protocol.js';
import {runDiagnosticAgent,reviewDiagnosticRun,diagnosticExecutionContract} from '../engine/diagnostic-execution.js';
import {createClarificationRun,clarificationFixture} from '../engine/clarification-experiment.js';
const contract=JSON.parse(await readFile(new URL('../evidence/clarification/contract.json',import.meta.url),'utf8'));
const event=text=>JSON.stringify({type:'item.completed',item:{type:'agent_message',text}})+'\n';
function harness(scripts){let calls=0,killed=0;const inputs=[];return {inputs,get calls(){return calls;},get killed(){return killed;},dependencies:{executable:'test-codex',cliVersion:'test-cli',createScratch:async()=>'.',launch(){const s=scripts[calls++];if(s.throwSpawn)throw Object.assign(Error('test spawn'),{code:'ENOENT'});const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin=new EventEmitter();child.kill=()=>{killed++;};child.stdin.end=text=>{inputs.push(text);if(s.throwInput)throw Error('test write');queueMicrotask(()=>{for(const b of s.stdout||[])child.stdout.emit('data',b);for(const b of s.stderr||[])child.stderr.emit('data',b);if(s.inputError)child.stdin.emit('error',Object.assign(Error('test input'),{code:'EPIPE'}));if(!s.hang)child.emit('close',s.exitCode??0,s.signal||null);});};return child;}}};}
async function rejectScript(script,options={}){const h=harness([script]),adapter=await diagnosticAdapter(baseline,null,{...h.dependencies,validate:validateAction,...options});await assert.rejects(adapter.next({ticket:'fictional'},undefined,1000));adapter.close();assert.equal(adapter.diagnostics.length,1);const d=adapter.diagnostics[0],{hash:digest,...v}=d;assert.equal(digest,hash(v));return {d,h,adapter};}
test('the diagnostic support prompt is exactly the frozen json-actions-2 wire prompt',async()=>{const old=await readFile(new URL('../engine/codex-adapter.js',import.meta.url),'utf8'),start=old.indexOf('`You are a support agent'),end=old.indexOf('${JSON.stringify(input)}`',start),literal=old.slice(start+1,end);assert.equal(diagnosticSupportPrompt,literal.replaceAll('\\n','\n'));});
test('invalid response JSON retains exact response bytes and a parser cause',async()=>{const response='Have you tried the steps?';const {d}=await rejectScript({stdout:[event(response)]});assert.equal(d.stage,'response_json');assert.equal(d.code,'invalid_response_json');assert.equal(d.response.text,response);assert.equal(Buffer.from(d.response.base64,'base64').toString(),response);assert.ok(d.details.parserMessage);});
test('stream JSON, missing message, native tool and schema failures remain distinct',async()=>{for(const [script,stage] of [[{stdout:['not-json\n']},'event_stream'],[{stdout:[JSON.stringify({type:'turn.completed'})+'\n']},'response_selection'],[{stdout:[JSON.stringify({item:{type:'web_search'}})+'\n']},'native_tool_policy'],[{stdout:[event('{"type":"final"}')]},'action_schema']])assert.equal((await rejectScript(script)).d.stage,stage);});
test('process start, write and exit failures retain their separate codes and stderr',async()=>{assert.equal((await rejectScript({throwSpawn:true})).d.code,'spawn_failed');assert.equal((await rejectScript({throwInput:true})).d.code,'stdin_failed');assert.equal((await rejectScript({inputError:true})).d.code,'stdin_failed');const {d}=await rejectScript({stdout:['partial'],stderr:['fictional CLI failure'],exitCode:7});assert.equal(d.stage,'process_exit');assert.equal(d.exitCode,7);assert.equal(d.stderr.text,'fictional CLI failure');assert.equal(d.stdout.text,'partial');});
test('valid action accepts chunked UTF-8 and retains no rejected-output receipt',async()=>{const action=clarificationFixture('execute-unknown').at(-1);action.reply='Please confirm the steps — thank you.';const b=Buffer.from(event(JSON.stringify(action))),split=b.indexOf(Buffer.from('—'))+1,h=harness([{stdout:[b.subarray(0,split),b.subarray(split)]}]),a=await diagnosticAdapter(baseline,null,{...h.dependencies,validate:validateAction});assert.deepEqual(await a.next({},undefined,1000),action);assert.equal(a.diagnostics.length,0);assert.equal(h.calls,1);assert.equal(h.inputs[0],diagnosticSupportPrompt+'{}');a.close();});
test('output and retention limits are byte bounded and disclose unobserved tail',async()=>{const {d}=await rejectScript({stdout:[Buffer.alloc(150000,120)]});assert.equal(d.code,'output_limit');assert.equal(d.stdout.bytes,128000);assert.equal(d.stdout.retainedBytes,diagnosticBounds.stdoutBytes);assert.equal(Buffer.from(d.stdout.base64,'base64').length,diagnosticBounds.stdoutBytes);assert.equal(d.stdout.truncated,true);assert.equal(d.details.unobservedTail,true);assert.equal(d.details.minimumOutputBytes,150000);});
test('timeout, cancellation and caller closure stop the process and retain partial output',async()=>{for(const mode of ['timeout','cancel','close']){const h=harness([{stdout:['partial'],hang:true}]),a=await diagnosticAdapter(baseline,null,h.dependencies),controller=new AbortController(),p=a.next({},controller.signal,mode==='timeout'?15:1000);await Promise.resolve();if(mode==='cancel')controller.abort();if(mode==='close')a.close();await assert.rejects(p);assert.equal(a.diagnostics[0].stage,{timeout:'timeout',cancel:'cancellation',close:'lifecycle'}[mode]);assert.equal(a.diagnostics[0].stdout.text,'partial');assert.ok(h.killed>0);}});
test('a rejected response persists through the real runner without entering agent-visible trace',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'taskwright-diag-run-')),run=createClarificationRun(contract,'execute-unknown',baseline);run.diagnosticExecution=diagnosticExecutionContract();const actions=clarificationFixture('execute-unknown'),h=harness([{stdout:[event(JSON.stringify(actions[0]))]},{stdout:[event(JSON.stringify(actions[1]))]},{stdout:[event('Not valid JSON')]}]);await runDiagnosticAgent(run,dir,undefined,h.dependencies);const saved=await readRun(dir,run.id);assert.equal(saved.status,'error');assert.equal(saved.final,null);assert.equal(saved.executionDiagnostics[0].stage,'response_json');assert.equal(saved.executionDiagnostics[0].response.text,'Not valid JSON');assert.equal(h.calls,3);assert.ok(h.inputs.every(s=>!s.includes('executionDiagnostics')));assert.ok(saved.trace.every(t=>!Object.hasOwn(t,'response')));assert.equal(saved.agent.execution.diagnosticExecutionHash,run.diagnosticExecution.hash);});
test('invalid review schema retains the rejected review instead of silently replacing it',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'taskwright-diag-review-')),run=createClarificationRun(contract,'prepare-unknown',baseline);run.diagnosticExecution=diagnosticExecutionContract();const actions=clarificationFixture('prepare-unknown'),h=harness(actions.map(a=>({stdout:[event(JSON.stringify(a))]})));await runDiagnosticAgent(run,dir,undefined,h.dependencies);const reviewer=harness([{stdout:[event('{"criteria":[]}')]}]),review=await reviewDiagnosticRun(run,{dependencies:reviewer.dependencies});assert.equal(review.status,'error');assert.equal(review.executionDiagnostics[0].stage,'review_schema');assert.equal(review.executionDiagnostics[0].response.text,'{"criteria":[]}');assert.equal(reviewer.calls,1);assert.equal(review.originalHash,hash(run));});
