import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {hash} from '../engine/scenario.js';
import {runAgent,saveRun} from '../engine/runner.js';
import {validateReview,dimensions} from '../engine/semantic.js';
import {clarificationFixture} from '../engine/clarification-experiment.js';
import {clarificationReviewInput,clarificationJudgeHash,clarificationReviewVersion} from '../engine/clarification-review.js';
import {createDiagnosticRerun,verifyDiagnosticRerun,executeDiagnosticRerun,summarizeDiagnosticRerun} from '../engine/diagnostic-rerun.js';
const read=async name=>JSON.parse(await readFile(new URL('../evidence/clarification/'+name+'.json',import.meta.url),'utf8')),original=await read('report'),calibration=await read('selected-calibration'),cli=calibration.plan.cliVersion;
const fresh=()=>createDiagnosticRerun(original,calibration,cli);
test('executed rerun reproduces its sealed first outcomes and keeps the original result separate',async()=>{
 const base=new URL('../evidence/diagnostic-rerun/',import.meta.url);
 const report=JSON.parse(await readFile(new URL('report.json',base),'utf8')),seal=JSON.parse(await readFile(new URL('seal.json',base),'utf8'));
 assert.equal(hash(report),seal.reportHash);assert.equal(report.plan.hash,seal.planHash);
 assert.equal(hash(summarizeDiagnosticRerun(report.plan,report.rows)),hash(report));
 assert.equal(report.rows.length,6);assert.equal(new Set(report.rows.map(r=>r.runId)).size,6);
 assert.ok(report.rows.every(r=>!['queued','running'].includes(r.run?.status)));
 assert.equal(report.plan.parentEvidence.reportHash,hash(original));assert.equal(original.decision,'incomplete');
 assert.ok(report.rows.every(r=>!original.rows.some(o=>o.runId===r.runId)));
 for(const r of report.rows){if(r.run?.status==='completed')assert.ok(Array.isArray(r.run.executionDiagnostics));if(r.review)assert.equal(r.review.originalHash,hash(r.run));}
});
test('retained declaration and scripted example reproduce with six frozen queued snapshots',async()=>{const plan=JSON.parse(await readFile(new URL('../evidence/diagnostic-rerun/plan.json',import.meta.url),'utf8')),runs=JSON.parse(await readFile(new URL('../evidence/diagnostic-rerun/scheduled-runs.json',import.meta.url),'utf8')),fixture=JSON.parse(await readFile(new URL('../evidence/diagnostic-rerun/fixture.json',import.meta.url),'utf8'));verifyDiagnosticRerun(plan,runs);assert.equal(plan.parentEvidence.reportHash,hash(original));assert.ok(runs.every(r=>r.final===null&&r.trace.length===0));const {hash:digest,...value}=fixture;assert.equal(digest,hash(value));assert.equal(fixture.run.mode,'replay');assert.equal(fixture.run.executionDiagnostics[0].code,'invalid_response_json');assert.equal(fixture.run.diagnosticExecution.hash,plan.diagnosticExecution.hash);});
function runtime(plan,review=false){return {cliVersion:cli,requestedModel:plan.controls.model,reasoningEffort:plan.controls.reasoningEffort,protocolVersion:review?clarificationReviewVersion:plan.controls.protocolVersion,diagnosticAdapterVersion:plan.diagnosticExecution.adapterVersion,diagnosticExecutionHash:plan.diagnosticExecution.hash};}
async function support(plan,run,dir){const actions=clarificationFixture(run.clarificationCell);let i=0;await runAgent(run,{metadata:runtime(plan),next:async()=>structuredClone(actions[i++])},dir);run.executionDiagnostics=[];await saveRun(dir,run);}
function review(plan,run){const input=clarificationReviewInput(run),raw={criteria:Object.keys(dimensions).map(id=>({id,outcome:'pass',claim:input.reply.slice(0,10),reason:'Synthetic plumbing test, not a model judgment.',evidence:[{source_id:'ticket',quote:input.evidence.ticket.slice(0,20)}]}))};return {id:randomUUID(),createdAt:new Date().toISOString(),runId:run.id,originalHash:hash(run),inputHash:hash(input),version:clarificationReviewVersion,judgeHash:clarificationJudgeHash,status:'completed',raw,evaluation:validateReview(raw,input),execution:runtime(plan,true),executionDiagnostics:[]};}
test('rerun freezes six new slots while retaining original task, configuration and incomplete result',()=>{const before=hash(original),{plan,runs}=fresh();assert.equal(runs.length,6);assert.equal(plan.parentEvidence.reportHash,before);assert.deepEqual(plan.contract,original.plan.contract);assert.deepEqual(plan.configuration,original.plan.configuration);assert.equal(plan.controls.calibrationHash,original.plan.controls.calibrationHash);assert.ok(runs.every(r=>!original.plan.schedule.some(s=>s.runId===r.id)));assert.equal(hash(original),before);assert.deepEqual(plan.schedule.map(s=>s.cell),['execute-unknown','prepare-unknown','prepare-unknown','execute-unknown','execute-unknown','prepare-unknown']);verifyDiagnosticRerun(plan,runs);const changed=structuredClone(runs);changed[0].agent.instructions='changed';assert.throws(()=>verifyDiagnosticRerun(plan,changed));});
test('an errored slot remains in the complete batch and the declaration cannot be executed twice',async()=>{const {plan,runs}=fresh(),initial=structuredClone(runs),dir=await mkdtemp(path.join(tmpdir(),'taskwright-diag-batch-'));let calls=0,reviews=0;const result=await executeDiagnosticRerun(plan,runs,dir,calibration,{runSupport:async(run,dir)=>{if(++calls===1)throw Error('Synthetic process failure');await support(plan,run,dir);},review:async run=>{reviews++;return review(plan,run);}});assert.equal(calls,6);assert.equal(reviews,5);assert.equal(result.decision,'incomplete');assert.equal(result.rows.length,6);assert.equal(result.rows[0].run.status,'error');assert.equal(result.rows.filter(r=>r.outcome==='pass').length,5);await assert.rejects(executeDiagnosticRerun(plan,initial,dir,calibration));assert.equal(calls,6);});
test('cancellation retains six cancelled records without calling support or review',async()=>{const {plan,runs}=fresh(),dir=await mkdtemp(path.join(tmpdir(),'taskwright-diag-cancel-')),c=new AbortController();c.abort();const result=await executeDiagnosticRerun(plan,runs,dir,calibration,{signal:c.signal,runSupport:()=>{throw Error('Must not execute');}});assert.ok(result.rows.every(r=>r.run.status==='cancelled'));assert.equal(result.decision,'incomplete');});
test('completed diagnostic evidence rejects changed execution identity or altered failure receipt',async()=>{const {plan,runs}=fresh(),dir=await mkdtemp(path.join(tmpdir(),'taskwright-diag-controls-'));const result=await executeDiagnosticRerun(plan,runs,dir,calibration,{runSupport:(r,d)=>support(plan,r,d),review:async r=>review(plan,r)});assert.equal(result.decision,'clarification_passed');const changed=structuredClone(result.rows);changed[0].run.agent.execution.diagnosticExecutionHash='different';changed[0].review=review(plan,changed[0].run);assert.equal(summarizeDiagnosticRerun(plan,changed).decision,'blocked');const receipt=structuredClone(result.rows);receipt[0].run.executionDiagnostics=[{stage:'response_json',hash:'invented'}];receipt[0].review=review(plan,receipt[0].run);assert.equal(summarizeDiagnosticRerun(plan,receipt).decision,'blocked');});
