import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createEligibilityContract,evaluateEligibility} from '../engine/eligibility.js';
import {authorityInstructions} from '../engine/authority.js';
import {createEligibilityRun,eligibilityFixture,eligibilityReferences} from '../engine/eligibility-experiment.js';
import {runAgent} from '../engine/runner.js';
import {eligibilityReviewInput} from '../engine/eligibility-review.js';
import {randomUUID} from 'node:crypto';
import {hash} from '../engine/scenario.js';
import {baseline} from '../engine/configurations.js';
import {dimensions,validateReview} from '../engine/semantic.js';
import {eligibilityReviewVersion,eligibilityJudgeHash} from '../engine/eligibility-review.js';
import {createEligibilityPlan,summarizeEligibility,executeEligibility,loadEligibility,validateEligibilityCalibration} from '../engine/eligibility-experiment.js';
import {saveRun} from '../engine/runner.js';
const dir=await mkdtemp(path.join(tmpdir(),'taskwright-eligibility-'));
async function replay(mode,kind){const contract=createEligibilityContract(mode),run=createEligibilityRun(contract,undefined,'replay'),actions=eligibilityFixture(contract,kind);let i=0,input;await runAgent(run,{next:async value=>{input=value;return actions[i++];}},dir);return {run,input};}
test('policy prerequisites override execute permission while the exact authority instructions stay unchanged',async()=>{
 for(const mode of ['execute','prepare']){const good=await replay(mode,'supported'),bad=await replay(mode,'premature');assert.equal(good.run.eligibilityContract.agentInstructions,authorityInstructions(good.run.eligibilityContract.fields));assert.equal(good.run.evaluation.criteria.find(c=>c.id==='handoff').outcome,'pass');assert.equal(bad.run.evaluation.criteria.find(c=>c.id==='handoff').outcome,'fail');assert.equal(good.run.scenario.split,'development');assert.equal(good.run.scenario.id,'vale-feed-first-steps');assert.ok(!JSON.stringify(good.input).includes('evaluationSpec'));assert.ok(!JSON.stringify(good.input).includes('reserved-'));}
});
test('false completion claims cannot change action counts and require a separate semantic verdict',async()=>{const {run}=await replay('execute','false_claim');assert.equal(run.evaluation.criteria.find(c=>c.id==='handoff').outcome,'pass');assert.match(run.final.reply,/I opened/);assert.equal(run.evaluation.outcome,'uncertain');const input=eligibilityReviewInput(run);assert.ok(input.evidence['doc:workspace-brief']);assert.ok(!Object.hasOwn(input,'reference'));});
test('eligibility grading requires both actual document reads and citations',async()=>{const {run}=await replay('execute','supported');run.final.evidence_ids=['product'];assert.equal(evaluateEligibility(run).criteria.find(c=>c.id==='sources').outcome,'fail');});
test('all authored eligibility traces reproduce expected task checks before semantic judgment',async()=>{for(const reference of eligibilityReferences){const {run}=await replay(reference.mode,reference.kind);const outcome=run.evaluation.criteria.filter(c=>c.id!=='writing').every(c=>c.outcome==='pass')?'pass':'fail';assert.equal(outcome,reference.task,reference.id);}});
function fakeReview(run,cliVersion,changes={}){const input=eligibilityReviewInput(run),raw={criteria:Object.keys(dimensions).map(id=>({id,outcome:changes[id]||'pass',claim:input.reply.slice(0,10),reason:'Synthetic test verdict, not an AI judgment.',evidence:[{source_id:'ticket',quote:input.evidence.ticket.slice(0,20)}]}))};return {id:randomUUID(),createdAt:new Date().toISOString(),runId:run.id,originalHash:hash(run),inputHash:hash(input),version:eligibilityReviewVersion,judgeHash:eligibilityJudgeHash,status:'completed',raw,evaluation:validateReview(raw,input),execution:{cliVersion,requestedModel:baseline.model,reasoningEffort:baseline.reasoningEffort,protocolVersion:eligibilityReviewVersion}};}
async function syntheticCalibration(){const report=JSON.parse(await readFile(new URL('../evidence/eligibility/calibration.json',import.meta.url),'utf8'));for(const result of report.results)result.review=fakeReview(result.run,report.plan.cliVersion,result.reference.targets);report.matches=8;const {hash:old,...value}=report;return {...value,hash:hash(value)};}
const adapter=(run,cliVersion)=>{const actions=eligibilityFixture(run.eligibilityContract);let i=0;return {metadata:{cliVersion,requestedModel:run.agent.model,reasoningEffort:run.agent.reasoningEffort,protocolVersion:run.agent.protocolVersion},next:async()=>actions[i++]};};
test('an errored first calibration remains a failed gate and cannot launch support trials',async()=>{const report=JSON.parse(await readFile(new URL('../evidence/eligibility/calibration.json',import.meta.url),'utf8'));assert.equal(validateEligibilityCalibration(report,report.plan.cliVersion).passed,false);assert.throws(()=>createEligibilityPlan(baseline,report.plan.cliVersion,report),/gate failed/);});
test('eligibility plan keeps six denominators and separates restraint from reply failures',async()=>{const calibration=await syntheticCalibration(),cli=calibration.plan.cliVersion,{plan,runs}=createEligibilityPlan(baseline,cli,calibration),records=[];assert.equal(new Set(runs.map(r=>r.id)).size,6);assert.deepEqual(plan.schedule.map(s=>s.mode),['execute','prepare','prepare','execute','execute','prepare']);for(const run of runs){await runAgent(run,adapter(run,cli),dir);records.push({run,review:fakeReview(run,cli)});}assert.equal(summarizeEligibility(plan,records).decision,'policy_restraint_demonstrated');const failed=structuredClone(records);failed[0].review=fakeReview(failed[0].run,cli,{completeness:'fail'});const result=summarizeEligibility(plan,failed);assert.equal(result.decision,'restraint_with_reply_failures');assert.equal(result.policyRestraint,true);assert.equal(result.rows[0].actions,'fail');const missing=structuredClone(records);missing[1].review=null;assert.equal(summarizeEligibility(plan,missing).decision,'incomplete');const drift=structuredClone(records);drift[0].run.agent.execution.cliVersion='different';assert.equal(summarizeEligibility(plan,drift).decision,'blocked');const quotes=structuredClone(records);quotes[0].review.raw.criteria[0].claim='invented';assert.equal(summarizeEligibility(plan,quotes).decision,'blocked');});
test('cancelling the eligibility batch preserves all attempts without starting adapters',async()=>{const calibration=await syntheticCalibration(),{plan,runs}=createEligibilityPlan(baseline,calibration.plan.cliVersion,calibration),controller=new AbortController();controller.abort();let calls=0;for(const run of runs)await saveRun(dir,run);await executeEligibility(runs,dir,{signal:controller.signal,makeAdapter:()=>{calls++;throw Error('Must not call');}});assert.equal(calls,0);assert.ok(runs.every(r=>r.status==='cancelled'));assert.equal((await loadEligibility(dir,plan)).decision,'incomplete');});
test('lost eligibility review remains missing while the remaining scheduled first attempts are retained',async()=>{const calibration=await syntheticCalibration(),cli=calibration.plan.cliVersion,{plan,runs}=createEligibilityPlan(baseline,cli,calibration);let reviews=0;for(const run of runs)await saveRun(dir,run);await executeEligibility(runs,dir,{makeAdapter:run=>adapter(run,cli),makeReview:async run=>{if(++reviews===1)throw Error('Synthetic review loss');return fakeReview(run,cli);}});const report=await loadEligibility(dir,plan);assert.equal(reviews,6);assert.equal(report.decision,'incomplete');assert.equal(report.rows.filter(r=>r.review).length,5);assert.equal(report.rows[0].review,null);assert.equal(JSON.parse(await readFile(`${dir}/review-errors/${runs[0].id}.json`,'utf8')).error,'Synthetic review loss');});
