import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { request } from 'node:http';
import {randomUUID} from 'node:crypto';
import {readRun,createRun,runAgent,replayAdapter} from '../engine/runner.js';
import {hash} from '../engine/scenario.js';
import {saveReview,judgeHash} from '../engine/semantic.js';
import {createAuthorityRun} from '../engine/authority-experiment.js';
import {authorityFixture} from '../engine/authority-fixtures.js';
import {createEligibilityContract} from '../engine/eligibility.js';
import {createEligibilityRun,eligibilityFixture} from '../engine/eligibility-experiment.js';
import {createRegressionContract} from '../engine/regression.js';
import {createRegressionRun,regressionFixture} from '../engine/regression-experiment.js';
import {createClarificationContract} from '../engine/clarification.js';
import {createClarificationRun,clarificationFixture} from '../engine/clarification-experiment.js';
test('local API rejects foreign callers and preserves runs across server restart',async t=>{
 const dir=await mkdtemp(path.join(tmpdir(),'taskwright-api-'));const port=43000+Math.floor(Math.random()*10000);const base=`http://127.0.0.1:${port}`;let child;
 const start=async(legacy=false)=>{let startupError='';child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PATH:'',PORT:String(port),TASKWRIGHT_RUN_DIR:legacy?'':dir,TRYWISE_RUN_DIR:legacy?dir:path.join(dir,'legacy-unused')},windowsHide:true,stdio:['ignore','pipe','pipe']});child.stderr.on('data',chunk=>startupError+=chunk.toString());await Promise.race([once(child.stdout,'data'),once(child,'exit').then(([code])=>{throw Error('Server exited before listening ('+code+'): '+startupError);})]);};
 const stop=async()=>{const p=once(child,'exit');child.kill();await p;};t.after(()=>child?.kill());await start();
 assert.equal((await fetch(base+'/')).status,200);
 assert.equal((await fetch(base+'/compare.html')).status,200);
 assert.equal((await fetch(base+'/calibration.html')).status,200);
 assert.equal((await fetch(base+'/suite.html')).status,200);
 assert.equal((await fetch(base+'/brief.html')).status,200);
 assert.equal((await fetch(base+'/authority.html')).status,200);
 assert.equal((await fetch(base+'/eligibility.html')).status,200);
 assert.equal((await fetch(base+'/regression.html')).status,200);
 assert.equal((await fetch(base+'/clarification.html')).status,200);
 assert.equal((await fetch(base+'/continuation-ui.js')).status,200);
 const continuationState=await(await fetch(base+'/api/continuation')).json();assert.equal(continuationState.plan.contract.version,6);assert.equal(continuationState.plan.schedule.length,12);assert.equal(continuationState.plan.calibration.length,12);
 assert.equal((await fetch(base+'/api/continuation/start',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 assert.equal((await fetch(base+'/api/continuation/start',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://untrusted.example'},body:'{}'})).status,403);
 assert.ok([400,409].includes((await fetch(base+'/api/continuation/start',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status));
 assert.equal((await fetch(base+'/diagnostics.html')).status,200);
 const savedDiagnosticReport=await readFile(new URL('../evidence/diagnostic-rerun/report.json',import.meta.url),'utf8').then(JSON.parse).catch(e=>{if(e.code!=='ENOENT')throw e;return null;});
 const diagnosticState=await(await fetch(base+'/api/diagnostic-rerun')).json();assert.equal(diagnosticState.status,savedDiagnosticReport?'finished':'predeclared_not_executed');assert.equal(diagnosticState.plan.schedule.length,6);assert.deepEqual(diagnosticState.report,savedDiagnosticReport);assert.equal(diagnosticState.fixture.run.mode,'replay');
 assert.equal((await fetch(base+'/api/diagnostic-rerun/start',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 assert.equal((await fetch(base+'/api/diagnostic-rerun/start',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://untrusted.example'},body:'{}'})).status,403);
 assert.equal((await fetch(base+'/api/diagnostic-rerun/start',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,savedDiagnosticReport?409:400);
 const clarificationState=await(await fetch(base+'/api/clarification')).json();assert.equal(clarificationState.calibration.contract.version,5);assert.equal(clarificationState.calibration.passed,false);assert.equal(clarificationState.calibration.report.matches,10);
 assert.deepEqual(await(await fetch(base+'/api/clarification/experiments')).json(),[]);
 const clarificationRun=createClarificationRun(createClarificationContract(),'execute-unknown',undefined,'replay');clarificationRun.clarificationExperiment={id:randomUUID()};const clarificationActions=clarificationFixture(clarificationRun.clarificationCell);let clarificationIndex=0;await runAgent(clarificationRun,{next:async()=>clarificationActions[clarificationIndex++]},dir);
 assert.equal((await fetch(base+`/api/runs/${clarificationRun.id}/review`,{method:'POST'})).status,409);
 assert.equal((await(await fetch(base+`/api/runs/${clarificationRun.id}/reassess`,{method:'POST'})).json()).evaluation.version,'authority-clarification-5');assert.deepEqual(await readRun(dir,clarificationRun.id),clarificationRun);
 assert.equal((await fetch(base+'/api/clarification/experiments',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 const regressionState=await(await fetch(base+'/api/regression')).json();assert.equal(regressionState.calibration.contract.version,4);assert.equal(regressionState.calibration.passed,false);assert.equal(regressionState.calibration.report.matches,12);
 assert.deepEqual(await(await fetch(base+'/api/regression/experiments')).json(),[]);
 const regressionRun=createRegressionRun(createRegressionContract(),'execute-unqualified',undefined,'replay');regressionRun.regressionExperiment={id:randomUUID()};const regressionActions=regressionFixture(regressionRun.regressionCell);let regressionIndex=0;await runAgent(regressionRun,{next:async()=>regressionActions[regressionIndex++]},dir);
 assert.equal((await fetch(base+`/api/runs/${regressionRun.id}/review`,{method:'POST'})).status,409);
 assert.equal((await(await fetch(base+`/api/runs/${regressionRun.id}/reassess`,{method:'POST'})).json()).evaluation.version,'authority-regression-4');assert.deepEqual(await readRun(dir,regressionRun.id),regressionRun);
 assert.equal((await fetch(base+'/api/regression/experiments',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 assert.equal((await fetch(base+'/api/regression/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({configuration:'support-baseline@1',contract:regressionState.calibration.contract.hash})})).status,400);
 const eligibilityEvidence=await(await fetch(base+'/api/eligibility')).json();assert.equal(eligibilityEvidence.calibrations[0].matches,7);
 const eligibilityContract=createEligibilityContract('execute'),eligibilityRun=createEligibilityRun(eligibilityContract,undefined,'replay');eligibilityRun.eligibilityExperiment={id:randomUUID()};const eligibilityActions=eligibilityFixture(eligibilityContract);let eligibilityIndex=0;await runAgent(eligibilityRun,{next:async()=>eligibilityActions[eligibilityIndex++]},dir);
 assert.equal((await fetch(base+`/api/runs/${eligibilityRun.id}/review`,{method:'POST'})).status,409);
 const eligibilityAssessment=await(await fetch(base+`/api/runs/${eligibilityRun.id}/reassess`,{method:'POST'})).json();assert.equal(eligibilityAssessment.evaluation.version,'authority-eligibility-3');assert.deepEqual(await readRun(dir,eligibilityRun.id),eligibilityRun);
 const authority=await(await fetch(base+'/api/authority')).json();assert.equal(authority.scenario.split,'development');assert.equal(authority.scenario.id,'vale-feed-handoff');
 const authorityResponse=await fetch(base+'/api/authority/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(authority.defaults)});assert.equal(authorityResponse.status,201);const authorityContract=await authorityResponse.json();
 assert.equal(authorityContract.fields.handoffAuthority,'prepare');assert.equal((await(await fetch(base+'/api/authority')).json()).contracts[0].hash,authorityContract.hash);
 const authorityRun=createAuthorityRun(authorityContract,authority.configurations[0],'replay');authorityRun.authorityExperiment={id:randomUUID()};const actions=authorityFixture(authorityContract);let actionIndex=0;await runAgent(authorityRun,{next:async()=>actions[actionIndex++]},dir);
 assert.equal((await fetch(base+`/api/runs/${authorityRun.id}/review`,{method:'POST'})).status,409);
 const reassessed=await(await fetch(base+`/api/runs/${authorityRun.id}/reassess`,{method:'POST'})).json();assert.equal(reassessed.evaluation.version,'authority-2');assert.deepEqual(await readRun(dir,authorityRun.id),authorityRun);
 const briefConfig=await(await fetch(base+'/api/briefs')).json();assert.equal(briefConfig.defaults.policyMode,'always');
 const briefResponse=await fetch(base+'/api/briefs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:briefConfig.defaults})});assert.equal(briefResponse.status,201);const brief=await briefResponse.json();
 const frozen=await(await fetch(base+`/api/briefs/${brief.id}/freeze`,{method:'POST'})).json();assert.equal(frozen.status,'frozen');
 const comparisonRun=createRun('replay','supported',undefined,'vale-wireless',frozen);comparisonRun.experiment={id:randomUUID()};await runAgent(comparisonRun,replayAdapter('supported'),dir);
 const replacement=await fetch(base+`/api/runs/${comparisonRun.id}/review`,{method:'POST'});assert.equal(replacement.status,409);assert.match((await replacement.json()).error,/first scheduled review/);
 assert.equal((await fetch(base+`/api/briefs/${brief.id}/freeze`,{method:'POST',headers:{Origin:'https://untrusted.example'}})).status,403);
 assert.equal((await fetch(base+'/api/contract-suites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contract:brief.id,baseline:'support-baseline@1',candidate:'support-baseline@1'})})).status,400);
 const suite=await(await fetch(base+'/api/suite')).json();assert.equal(suite.plan.reservation.count,4);assert.equal(suite.rows.length,16);
 assert.ok(!JSON.stringify(suite).includes('Nia:'));
 assert.equal((await fetch(base+'/evidence/conditional-handoff/reservation.json')).status,404);
 assert.equal((await(await fetch(base+'/api/config')).json()).scenarios.length,4);
 assert.equal((await(await fetch(base+'/api/calibration')).json()).report.records.length,16);
 const configs=(await(await fetch(base+'/api/config')).json()).configurations;
 assert.equal(configs[0].model,'gpt-6-astra');
 const version=await fetch(base+'/api/configurations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'API candidate',instructions:'Read the applicable policy before replying.',parent:'support-candidate@1'})});assert.equal(version.status,201);
 const saved=await version.json();assert.equal(saved.version,2);
 assert.equal((await fetch(base+'/api/configurations',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'})).status,403);
 assert.equal((await fetch(base+'/api/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"baseline":"nonexistent","candidate":"support-candidate@1","repetitions":2}'})).status,400);
 const hostStatus=await new Promise((resolve,reject)=>{const req=request(base+'/api/config',{headers:{Host:'untrusted.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(hostStatus,403);
 assert.equal((await fetch(base+'/api/runs',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{"mode":"codex"}'})).status,403);
 assert.equal((await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 const response=await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"mode":"replay","fixture":"supported"}'});assert.equal(response.status,202);const {id}=await response.json();
 let run;for(let i=0;i<40;i++){run=await(await fetch(base+'/api/runs/'+id)).json();if(run.evaluation)break;await new Promise(r=>setTimeout(r,20));}
 assert.equal(run.status,'completed');assert.equal(run.mode,'replay');assert.equal(run.evaluation.outcome,'uncertain');await stop();await start(true);assert.deepEqual(await(await fetch(base+'/api/runs/'+id)).json(),run);
 assert.equal((await fetch(base+'/data/runs/'+id+'.json')).status,404);
 assert.equal((await(await fetch(base+'/api/config')).json()).configurations.at(-1).hash,saved.hash);
 const fakeReview={id:randomUUID(),runId:id,originalHash:hash(await readRun(dir,id)),judgeHash,status:'completed',kind:'stored test fixture',evaluation:{outcome:'uncertain',criteria:[]}};await saveReview(dir,fakeReview);
 assert.deepEqual(await(await fetch(base+`/api/runs/${id}/review`,{method:'POST'})).json(),fakeReview);
 assert.equal((await fetch(base+`/api/runs/${id}/review`,{method:'POST',headers:{Origin:'https://untrusted.example'}})).status,403);
 const annotated=await(await fetch(base+'/api/runs/'+id)).json();assert.equal(annotated.reviews[0].matchesRun,true);assert.deepEqual(annotated.evaluation,run.evaluation);
 await stop();
});
