import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { request } from 'node:http';
import {randomUUID} from 'node:crypto';
import {readRun,createRun,runAgent,replayAdapter} from '../engine/runner.js';
import {hash} from '../engine/scenario.js';
import {saveReview,judgeHash} from '../engine/semantic.js';
test('local API rejects foreign callers and preserves runs across server restart',async t=>{
 const dir=await mkdtemp(path.join(tmpdir(),'taskwright-api-'));const port=43000+Math.floor(Math.random()*10000);const base=`http://127.0.0.1:${port}`;let child;
 const start=async(legacy=false)=>{child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PATH:'',PORT:String(port),TASKWRIGHT_RUN_DIR:legacy?'':dir,TRYWISE_RUN_DIR:legacy?dir:path.join(dir,'legacy-unused')},windowsHide:true,stdio:['ignore','pipe','pipe']});await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw Error('Server exited before listening');})]);};
 const stop=async()=>{const p=once(child,'exit');child.kill();await p;};t.after(()=>child?.kill());await start();
 assert.equal((await fetch(base+'/')).status,200);
 assert.equal((await fetch(base+'/compare.html')).status,200);
 assert.equal((await fetch(base+'/calibration.html')).status,200);
 assert.equal((await fetch(base+'/suite.html')).status,200);
 assert.equal((await fetch(base+'/brief.html')).status,200);
 const briefConfig=await(await fetch(base+'/api/briefs')).json();assert.equal(briefConfig.defaults.policyMode,'always');
 const briefResponse=await fetch(base+'/api/briefs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:briefConfig.defaults})});assert.equal(briefResponse.status,201);const brief=await briefResponse.json();
 const frozen=await(await fetch(base+`/api/briefs/${brief.id}/freeze`,{method:'POST'})).json();assert.equal(frozen.status,'frozen');
 const comparisonRun=createRun('replay','supported',undefined,'vale-wireless',frozen);comparisonRun.experiment={id:randomUUID()};await runAgent(comparisonRun,replayAdapter('supported'),dir);
 const replacement=await fetch(base+`/api/runs/${comparisonRun.id}/review`,{method:'POST'});assert.equal(replacement.status,409);assert.match((await replacement.json()).error,/first scheduled review/);
 assert.equal((await fetch(base+`/api/briefs/${brief.id}/freeze`,{method:'POST',headers:{Origin:'https://untrusted.example'}})).status,403);
 assert.equal((await fetch(base+'/api/contract-suites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contract:brief.id,baseline:'support-baseline@1',candidate:'support-baseline@1'})})).status,400);
 const suite=await(await fetch(base+'/api/suite')).json();assert.equal(suite.plan.reservation.count,4);assert.equal(suite.rows.length,16);
 assert.ok(!JSON.stringify(suite).includes('Nia:'));
 assert.equal((await fetch(base+'/evidence/conditional-handoff/reservation.json')).status,404);
 assert.equal((await(await fetch(base+'/api/config')).json()).scenarios.length,4);
 assert.equal((await(await fetch(base+'/api/calibration')).json()).report.records.length,16);
 const configs=(await(await fetch(base+'/api/config')).json()).configurations;
 assert.equal(configs[0].model,'gpt-6-astra');
 const version=await fetch(base+'/api/configurations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'API candidate',instructions:'Read the applicable policy before replying.',parent:'support-candidate@1'})});assert.equal(version.status,201);
 const saved=await version.json();assert.equal(saved.version,2);
 assert.equal((await fetch(base+'/api/configurations',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'})).status,403);
 assert.equal((await fetch(base+'/api/experiments',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"baseline":"nonexistent","candidate":"support-candidate@1","repetitions":2}'})).status,400);
 const hostStatus=await new Promise((resolve,reject)=>{const req=request(base+'/api/config',{headers:{Host:'untrusted.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(hostStatus,403);
 assert.equal((await fetch(base+'/api/runs',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{"mode":"codex"}'})).status,403);
 assert.equal((await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})).status,415);
 const response=await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"mode":"replay","fixture":"supported"}'});assert.equal(response.status,202);const {id}=await response.json();
 let run;for(let i=0;i<40;i++){run=await(await fetch(base+'/api/runs/'+id)).json();if(run.evaluation)break;await new Promise(r=>setTimeout(r,20));}
 assert.equal(run.status,'completed');assert.equal(run.mode,'replay');assert.equal(run.evaluation.outcome,'uncertain');await stop();await start(true);assert.deepEqual(await(await fetch(base+'/api/runs/'+id)).json(),run);
 assert.equal((await fetch(base+'/data/runs/'+id+'.json')).status,404);
 assert.equal((await(await fetch(base+'/api/config')).json()).configurations.at(-1).hash,saved.hash);
 const fakeReview={id:randomUUID(),runId:id,originalHash:hash(await readRun(dir,id)),judgeHash,status:'completed',kind:'stored test fixture',evaluation:{outcome:'uncertain',criteria:[]}};await saveReview(dir,fakeReview);
 assert.deepEqual(await(await fetch(base+`/api/runs/${id}/review`,{method:'POST'})).json(),fakeReview);
 assert.equal((await fetch(base+`/api/runs/${id}/review`,{method:'POST',headers:{Origin:'https://untrusted.example'}})).status,403);
 const annotated=await(await fetch(base+'/api/runs/'+id)).json();assert.equal(annotated.reviews[0].matchesRun,true);assert.deepEqual(annotated.evaluation,run.evaluation);
 await stop();
});
