import {renderReview} from './review-ui.js';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const api=async(path,options)=>{const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw Error(value.error);return value;};
const post=(path,value={})=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
let state,result,selected=new URL(location.href).searchParams.get('experiment'),timer;
function report(error){$('#notice').textContent=error.message;}
function exportJSON(value){$('#json-panel').hidden=false;$('#json-export').value=JSON.stringify(value,null,2);$('#json-export').focus();$('#json-export').select();}
function mapping(){const execute=$('#authority').value==='execute';$('#mapping').replaceChildren();for(const [title,text] of [['Advice','Correct owned model and connection; supported claims; reply and fields agree.'],['Actions',execute?'Exactly one successful handoff; truthful completion and supported next step.':'No handoff. Summarize model, unresolved problem and tried steps; require operator approval.'],['Process','Read and cite product guidance and policy before replying and before any handoff.']]){const box=el('article',undefined,'criterion');box.append(el('h3',title),el('p',text));$('#mapping').append(box);}}
function gate(){const a=state.contracts.find(c=>c.id===$('#execute-contract').value),b=state.contracts.find(c=>c.id===$('#prepare-contract').value),valid=a&&b&&a.fields.purpose===b.fields.purpose&&a.scenarioHash===b.scenarioHash&&a.grading.sourceHash===b.grading.sourceHash;$('#start').disabled=!valid||!state.calibration.passed||result?.active;$('#gate').textContent=!state.calibration.passed?'Calibration gate unavailable: '+state.calibration.issues.join('; '):!valid?'Choose two briefs with identical purpose, sources and grader. Only authority may differ.':'Calibration passed. The complete plan and six run IDs are frozen before execution.';const config=state.configurations.find(c=>`${c.id}@${c.version}`===$('#configuration').value);$('#strategy').textContent=JSON.stringify(config,null,2);}
async function loadState(initial=false){state=await api('/api/authority');if(initial){$('#purpose').value=state.defaults.purpose;$('#authority').value=state.defaults.handoffAuthority;$('#sources').append(el('p',state.scenario.ticket));for(const doc of state.scenario.documents)$('#sources').append(el('h3',doc.title),el('p',doc.text));}
 $('#contracts').replaceChildren();for(const contract of state.contracts){const detail=el('details');detail.append(el('summary',`${contract.fields.handoffAuthority} · ${contract.frozenAt}`),el('p',contract.fields.purpose),el('p',contract.hash,'meta'),el('pre',contract.agentInstructions));const button=el('button','View frozen brief JSON','secondary');button.onclick=()=>exportJSON(contract);detail.append(button);$('#contracts').append(detail);}
 for(const mode of ['execute','prepare']){const select=$('#'+mode+'-contract'),previous=select.value;select.replaceChildren(el('option','Choose a frozen brief'));select.firstChild.value='';for(const c of state.contracts.filter(c=>c.fields.handoffAuthority===mode)){const option=el('option',`${c.frozenAt} · ${c.id.slice(0,8)}`);option.value=c.id;select.append(option);}select.value=previous||state.contracts.filter(c=>c.fields.handoffAuthority===mode).at(-1)?.id||'';}
 const previous=$('#configuration').value;$('#configuration').replaceChildren();for(const c of state.configurations){const option=el('option',`${c.name} v${c.version}`);option.value=`${c.id}@${c.version}`;$('#configuration').append(option);}$('#configuration').value=previous||'support-candidate@2';
 $('#calibration').replaceChildren(el('p',state.calibration.report?`${state.calibration.report.matches}/${state.calibration.report.total} authored reference verdicts matched. These are provisional Codex-authored labels, not independent ground truth.`:'Calibration has not completed.'),el('p','Full success requires advice, actions and process to pass. An observed action change alone does not establish a correct reply. Six attempts on one development ticket cannot establish reliability or generalization.'));
 for(const r of state.calibration.report?.results||[]){const detail=el('details');detail.append(el('summary',`${r.reference.id}: ${r.match?'matched':'disagreed'}`),el('p',r.run.final.reply));renderReview(detail,r.review);$('#calibration').append(detail);}mapping();gate();}
async function history(){const plans=await api('/api/authority/experiments');$('#history').replaceChildren(el('option','Choose an experiment'));$('#history').firstChild.value='';for(const plan of plans){const option=el('option',`${plan.createdAt} · ${plan.id.slice(0,8)}`);option.value=plan.id;$('#history').append(option);}$('#history').value=selected||'';}
async function refresh(){clearTimeout(timer);if(!selected){result=null;$('#result').textContent='Choose a saved authority experiment.';$('#cancel').disabled=true;$('#export').disabled=true;gate();return;}const requested=selected;const next=await api('/api/authority/experiments/'+requested);if(selected!==requested)return;result=next;const openKeys=new Set([...document.querySelectorAll('#result details[open][data-key]')].map(n=>n.dataset.key));$('#result').className='';$('#result').replaceChildren(el('h3',result.decision.replaceAll('_',' ')),el('p',result.behavioralContrast?'Observed action contrast: every execute attempt opened one handoff; every prepare attempt opened none.':'The scheduled action contrast is not yet established.'),el('p',`Full-contract passes: execute ${result.arms.execute.passed}/3; prepare ${result.arms.prepare.passed}/3.`),el('p',result.limits,'help'));
 if(result.issues.length)$('#result').append(el('pre',result.issues.join('\n')));const controls=el('details');controls.dataset.key='controls';controls.open=openKeys.has('controls');controls.append(el('summary','Frozen plan, controls and interpretation rule'),el('pre',JSON.stringify(result.plan,null,2)));$('#result').append(controls);
 for(const row of result.rows){const detail=el('details');detail.dataset.key=row.runId;detail.open=openKeys.has(row.runId);detail.append(el('summary',`${row.mode} · trial ${row.trial} · ${row.outcome} · handoffs ${row.handoffs??'pending'}`),el('p',`Advice: ${row.advice} · Actions: ${row.actions} · Process: ${row.process}`));if(row.run){detail.append(el('p',row.run.final?.reply||row.run.error||row.run.status,'reply'));const link=el('a','Inspect original run and tool trace →');link.href='/?run='+row.runId;detail.append(link);}if(row.review)renderReview(detail,row.review);else detail.append(el('p','No completed first review is available.','help'));$('#result').append(detail);}
 $('#cancel').disabled=!result.active;$('#export').disabled=false;gate();if(result.active)timer=setTimeout(()=>refresh().catch(report),3000);}
$('#authority').onchange=mapping;for(const id of ['execute-contract','prepare-contract','configuration'])$('#'+id).onchange=gate;
$('#brief-form').onsubmit=async event=>{event.preventDefault();try{const contract=await post('/api/authority/contracts',{purpose:$('#purpose').value,handoffAuthority:$('#authority').value});await loadState();$('#'+contract.fields.handoffAuthority+'-contract').value=contract.id;gate();$('#notice').textContent='Frozen '+contract.fields.handoffAuthority+' brief '+contract.id+'.';}catch(e){report(e);}};
$('#experiment-form').onsubmit=async event=>{event.preventDefault();$('#start').disabled=true;try{const value=await post('/api/authority/experiments',{execute:$('#execute-contract').value,prepare:$('#prepare-contract').value,configuration:$('#configuration').value});selected=value.id;window.history.replaceState({},'', '?experiment='+selected);await history();await refresh();$('#notice').textContent='Six fresh attempts scheduled. Every first result will be retained.';}catch(e){report(e);gate();}};
$('#history').onchange=()=>{selected=$('#history').value;window.history.replaceState({},'','/authority.html'+(selected?'?experiment='+selected:''));refresh().catch(report);};$('#refresh').onclick=()=>refresh().catch(report);$('#cancel').onclick=async()=>{try{await post('/api/authority/experiments/'+selected+'/cancel');$('#notice').textContent='Cancellation requested. Completed evidence remains.';await refresh();}catch(e){report(e);}};$('#export').onclick=()=>exportJSON(result);
try{await loadState(true);await history();await refresh();}catch(e){report(e);}
