import {renderReview} from './review-ui.js';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
try{
 const response=await fetch('/api/calibration');if(!response.ok)throw Error('Calibration unavailable');const {report,currentJudgeHash}=await response.json();
 if(!report){$('#notice').textContent='Calibration is not complete. No agreement or readiness claim is available.';}else{
  $('#summary').append(el('h2',report.pilotGate?'Pilot calibration gate met':'Pilot calibration gate not met'),el('p',report.rule),el('p',`Judge: ${report.semanticVersion} · Reference set: ${report.referenceVersion} · Current prompt matches: ${report.judgeHash===currentJudgeHash?'yes':'no'}`,'meta'));
  const grid=el('div',undefined,'metric-grid');for(const [split,s]of Object.entries(report.bySplit)){const box=el('article',undefined,'metric-card');box.append(el('h3',split),el('p',`${s.agreement} / ${s.scheduled} agree`,'big-number'),el('p',`${s.completed} valid reviews · ${s.falsePasses} false passes · ${s.targetMatches}/${s.targetCount} targeted dimensions agree`));grid.append(box);}$('#summary').append(grid);
  const refs=await (await fetch('/api/calibration/references')).json();
  const open=record=>{const ref=refs.find(c=>c.id===record.caseId),root=$('#case');root.replaceChildren();root.append(el('h2',`${record.caseId} · ${ref.category}`),el('p',`${ref.split} · Reference: ${record.reference.outcome} · Judge: ${record.review.evaluation?.outcome||'unavailable'}`),el('p',record.reference.reason),el('h3','Reply under review'),el('p',ref.run.final.reply,'reply'));renderReview(root,record.review);const input=el('details');input.append(el('summary','Reference source documents and trace'),el('pre',JSON.stringify(ref.run,null,2)));root.append(input);for(const b of $('#cases').children)b.toggleAttribute('aria-current',b.dataset.id===record.caseId);};
  for(const record of report.records){const b=el('button',undefined,'run-item');b.dataset.id=record.caseId;const matches=record.reference.outcome===record.review.evaluation?.outcome;b.append(el('strong',`${record.caseId} · ${refs.find(c=>c.id===record.caseId).category}`),el('small',`${record.reference.outcome} → ${record.review.evaluation?.outcome||'unavailable'} · ${matches?'agrees':'disagrees'}`));b.onclick=()=>open(record);$('#cases').append(b);}if(report.records.length)open(report.records.find(r=>r.reference.outcome!==r.review.evaluation?.outcome)||report.records[0]);
 }
}catch(error){$('#notice').textContent=error.message;}
