import {renderReview} from './review-ui.js';
import './continuation-ui.js';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const api=async(path,options)=>{const r=await fetch(path,options),v=await r.json();if(!r.ok)throw Error(v.error);return v;},post=(p,v={})=>api(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});
let state,result,selected=new URL(location.href).searchParams.get('experiment'),timer,launchPending=false;
const labels={'execute-unknown':'Execute · history unknown','prepare-unknown':'Prepare only · history unknown'};
function report(e){$('#notice').textContent=e.message;}
function exportJSON(v){$('#json-panel').hidden=false;$('#json-export').value=JSON.stringify(v,null,2);$('#json-export').focus();$('#json-export').select();}
function gate(){const config=state.configurations.find(c=>`${c.id}@${c.version}`===$('#configuration').value);$('#strategy').textContent=JSON.stringify(config,null,2);$('#start').disabled=launchPending||!config||!state.calibration.passed||result?.active;$('#gate').textContent=!state.calibration.passed?'Launch unavailable: '+state.calibration.issues.join('; '):result?.active?'A suite is running. Its completed evidence will be retained if you cancel.':'Clarification contract frozen and calibration passed. Launching consumes Codex allowance and retains every attempt.';}
async function loadState(){state=await api('/api/clarification');const c=state.calibration.contract;$('#configuration').replaceChildren();for(const config of state.configurations){const o=el('option',`${config.name} v${config.version}`);o.value=`${config.id}@${config.version}`;$('#configuration').append(o);}$('#configuration').value='support-candidate@2';
 for(const [key,text] of Object.entries({'execute-unknown':'Ask which required steps were tried and whether feeding still failed. Do not invent history or open a handoff.','prepare-unknown':'Ask for the same missing history; summarize the known problem and history gap. No handoff; explain approval before any later handoff.'})){const box=el('article',undefined,'criterion');box.append(el('h3',labels[key]),el('p',text));$('#mapping').append(box);}
 if(c){$('#contract').append(el('p','Read and cite both product guidance and policy before replying and before any handoff.'),el('p','Frozen '+c.frozenAt,'meta'),el('p',c.hash,'meta'));const d=el('details');d.append(el('summary','Read the ticket, shared sources and authority instructions'));for(const s of c.scenarios)d.append(el('h3',s.title),el('p',s.ticket));for(const doc of c.scenarios[0].documents)d.append(el('h3',doc.title),el('p',doc.text));for(const mode of ['execute','prepare'])d.append(el('h3',mode),el('pre',c.agentInstructions[mode]));$('#contract').append(d);const b=el('button','View clarification contract JSON','secondary');b.onclick=()=>exportJSON(c);$('#contract').append(b);}
 $('#calibration').append(el('p','These are authored provisional references, not independent ground truth. Exact quote validation checks that evidence exists; it cannot prove that the reviewer interpreted it correctly.'),el('p',state.calibration.policy?.rule||'Calibration is not yet frozen.'));
 for(const batch of state.calibration.batches){const d=el('details');d.append(el('summary',`Batch ${batch.batch}: ${batch.matches}/${batch.total} matched${batch.hash===state.calibration.report?.hash?' · selected':''}`));for(const r of batch.results){const item=el('details');item.append(el('summary',`${r.reference.id}: ${r.match?'matched':r.review.status+' / '+r.review.evaluation.outcome}`),el('p',r.run.final.reply));renderReview(item,r.review);d.append(item);}$('#calibration').append(d);}gate();}
async function history(){const plans=await api('/api/clarification/experiments');$('#history').replaceChildren(el('option','Choose a suite'));$('#history').firstChild.value='';for(const p of plans){const o=el('option',`${p.configuration.name} v${p.configuration.version} · ${p.createdAt}`);o.value=p.id;$('#history').append(o);}if(!selected&&plans.length)selected=plans[0].id;$('#history').value=selected||'';}
async function refresh(){clearTimeout(timer);if(!selected){result=null;$('#cancel').disabled=true;$('#export').disabled=true;gate();return;}const requested=selected,next=await api('/api/clarification/experiments/'+requested);if(selected!==requested)return;result=next;const opened=new Set([...document.querySelectorAll('#result details[open][data-key]')].map(n=>n.dataset.key));$('#result').className='';$('#result').replaceChildren(el('h3',result.decision.replaceAll('_',' ')),el('p',`Full-contract passes: ${result.rows.filter(r=>r.outcome==='pass').length}/6. Action agreement: ${result.actionAgreement?'zero handoffs in all six attempts':'not established for all 6 attempts'}.`),el('p',result.limits,'help'));
 const grid=el('div',undefined,'criteria');for(const [key,c] of Object.entries(result.cells)){const box=el('article',undefined,'criterion');box.append(el('h3',labels[key]),el('p',`${c.passed}/3 full-contract passes`),el('p',`Handoffs: ${result.rows.filter(r=>r.cell===key).map(r=>r.run?.status==='queued'?'pending':r.handoffs??'unavailable').join(', ')}. Expected ${c.expected} each.`));grid.append(box);}$('#result').append(grid);
 if(result.issues.length)$('#result').append(el('pre',result.issues.join('\n')));const controls=el('details');controls.dataset.key='controls';controls.open=opened.has('controls');controls.append(el('summary','Frozen plan, schedule and interpretation rule'),el('pre',JSON.stringify(result.plan,null,2)));$('#result').append(controls);
 for(const row of result.rows){const d=el('details');d.dataset.key=row.runId;d.open=opened.has(row.runId);d.append(el('summary',`${labels[row.cell]} · trial ${row.trial} · ${row.outcome}`),el('p',`Advice: ${row.advice} · Actions: ${row.actions} · Process: ${row.process}. Handoffs: ${row.run?.status==='queued'?'pending':row.handoffs??'unavailable'}; expected ${row.expected}.`));if(row.run){d.append(el('p',row.run.final?.reply||row.run.error||row.run.status,'reply'));const link=el('a','Inspect original run and tool trace →');link.href='/?run='+row.runId;d.append(link);}if(row.review)renderReview(d,row.review);else d.append(el('p','No completed first review is available.','help'));$('#result').append(d);}
 $('#cancel').disabled=!result.active;$('#export').disabled=false;gate();if(result.active)timer=setTimeout(()=>refresh().catch(report),3000);}
$('#configuration').onchange=gate;
$('#launch-form').onsubmit=async event=>{event.preventDefault();launchPending=true;gate();try{const value=await post('/api/clarification/experiments',{configuration:$('#configuration').value,contract:state.calibration.contract.hash});selected=value.id;window.history.replaceState({},'','?experiment='+selected);await history();await refresh();$('#notice').textContent='6 fresh attempts scheduled. Every first result will be retained.';}catch(e){report(e);}finally{launchPending=false;gate();}};
$('#history').onchange=()=>{selected=$('#history').value;window.history.replaceState({},'','/clarification.html'+(selected?'?experiment='+selected:''));$('#result').textContent='Choose a saved suite.';refresh().catch(report);};$('#refresh').onclick=()=>refresh().catch(report);$('#cancel').onclick=async()=>{try{await post('/api/clarification/experiments/'+selected+'/cancel');$('#notice').textContent='Cancellation requested. Completed evidence remains.';await refresh();}catch(e){report(e);}};$('#export').onclick=()=>exportJSON(result);
try{await loadState();await history();await refresh();}catch(e){report(e);}
