import {renderReview} from './review-ui.js';
import {renderDiagnostics} from './diagnostic-ui.js';
const $=s=>document.querySelector(s),el=(t,v)=>{const n=document.createElement(t);if(v!==undefined)n.textContent=v;return n;};let state,timer;
async function refresh(){clearTimeout(timer);const response=await fetch('/api/diagnostic-rerun');state=await response.json();if(!response.ok)throw Error(state.error);$('#plan').replaceChildren(el('p',state.status.replaceAll('_',' ')));if(state.plan){$('#plan').append(el('p',state.plan.hash),el('p','Execution contract: '+state.plan.diagnosticExecution.hash));const d=el('details');d.append(el('summary','Frozen schedule and execution controls'),el('pre',JSON.stringify(state.plan,null,2)));$('#plan').append(d);const list=el('ol');for(const s of state.plan.schedule)list.append(el('li',`${s.cell} · trial ${s.trial} · ${s.runId}`));$('#plan').append(list);}
 $('#fixture').replaceChildren();if(state.fixture){$('#fixture').append(el('p',state.fixture.label));renderDiagnostics($('#fixture'),state.fixture.run.executionDiagnostics);}
 $('#result').replaceChildren();if(state.report){$('#result').append(el('h3',state.status==='running'?'Batch running · results provisional':state.report.decision),el('p',`${state.report.rows.filter(r=>r.outcome==='pass').length}/6 full-contract passes`));for(const row of state.report.rows){const d=el('details');d.append(el('summary',`${row.cell} · trial ${row.trial} · ${row.outcome}`),el('p',row.run?.final?.reply||row.run?.error||'No completed reply'));renderDiagnostics(d,row.run?.executionDiagnostics);if(row.run){const link=el('a','Inspect original run');link.href='/?run='+row.runId;d.append(link);}if(row.review)renderReview(d,row.review);$('#result').append(d);}}
 $('#cancel').disabled=state.status!=='running';if(state.status==='running')timer=setTimeout(()=>refresh().catch(showError),3000);}
function showError(e){$('#notice').textContent=e.message;}
$('#refresh').onclick=()=>refresh().catch(showError);$('#cancel').onclick=async()=>{try{const r=await fetch('/api/diagnostic-rerun/cancel',{method:'POST'});if(!r.ok)throw Error('Cancellation request failed');await refresh();}catch(e){showError(e);}};$('#export').onclick=()=>{$('#json-panel').hidden=false;$('#json-export').value=JSON.stringify(state,null,2);$('#json-export').focus();$('#json-export').select();};await refresh().catch(showError);
