import {renderDiagnostics} from './diagnostic-ui.js';
import {renderReview} from './review-ui.js';
const $=s=>document.querySelector(s);let scenarioOptions=[];let selected=null,poll=null,currentRun=null,renderKey=null;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,options){const res=await fetch(path,options);const data=await res.json();if(!res.ok)throw Error(data.error);return data;}
const badge=text=>el('span',text,`badge ${text}`);
function setMode(){const fresh=$('#mode').value==='codex';$('#fixture').disabled=fresh;$('#configuration').disabled=!fresh;$('#mode-help').textContent=fresh?'Fresh model calls through the signed-in CLI. Fictional task data is sent to Codex. Native tools are disabled; the lab executes only its allowlisted simulation tools.':'Scripted actions test the environment. They do not measure an agent.';}
$('#mode').addEventListener('change',setMode);
function setScenario(){const chosen=scenarioOptions.find(s=>s.id===$('#scenario').value);if(!chosen)return;$('#fixture').replaceChildren();for(const [id,title]of Object.entries(chosen.fixtures)){const o=el('option',title);o.value=id;$('#fixture').append(o);}$('#task-title').textContent=chosen.title;$('#task-description').textContent=chosen.ticket;$('#sources').replaceChildren();for(const d of chosen.documents){const box=el('article');box.append(el('h3',d.title),el('p',d.text));$('#sources').append(box);}}
$('#scenario').onchange=setScenario;
async function refresh(){
 const runs=await api('/api/runs');$('#history').replaceChildren();if(!runs.length)$('#history').append(el('p','No runs yet. Start with a replay.'));
 for(const run of runs){const b=el('button',undefined,'run-item');if(run.id===selected)b.setAttribute('aria-current','true');b.append(el('strong',run.mode==='replay'?run.fixture:(run.configuration||'Codex · legacy configuration')),el('small',run.scenarioTitle||''),el('small',new Date(run.createdAt).toLocaleString()),badge(run.status),el('small',run.outcome?'Original: '+run.outcome:(['queued','running'].includes(run.status)?'Awaiting evaluation':'Assessment unavailable')));b.onclick=()=>openRun(run.id);$('#history').append(b);}
 $('#start').disabled=runs.some(r=>['running','queued'].includes(r.status));
}
function render(run){
 currentRun=run;const result=run.assessments?.at(-1)?.evaluation||run.evaluation;const root=$('#detail');root.replaceChildren();const head=el('div',undefined,'run-head');
 head.append(badge(run.mode==='replay'?'replay':'fresh agent'),el('h2',run.mode==='replay'?`Replay · ${run.fixture}`:`Codex · ${run.agent.name||'Legacy configuration'} v${run.agent.version}`),badge(run.status),el('p',`${run.id} · ${run.scenario.id} ${run.scenario.version}`,'meta'));root.append(head,el('p',run.scenario.title),el('p',run.scenario.ticket,'help'));
 if(run.continuation){const d=el("details");d.append(el("summary","Customer continuation: "+run.continuation.mode+" / "+run.continuation.history),el("pre",JSON.stringify(run.continuation.conversation,null,2)));const a=el("a","Back to customer follow-up →");a.href="/clarification.html#continuation";d.append(a);root.append(d);} if(run.clarificationContract){const details=el("details");details.append(el("summary","Missing-history clarification: "+run.clarificationCell),el("pre",JSON.stringify(run.clarificationContract,null,2)));const link=el("a","Back to clarification test →");link.href="/clarification.html?experiment="+run.clarificationExperiment.id;details.append(link);root.append(details);} if(run.regressionContract){const details=el("details");details.append(el("summary","Shared authority regression: "+run.regressionCell),el("pre",JSON.stringify(run.regressionContract,null,2)));const link=el("a","Back to authority regression →");link.href="/regression.html?experiment="+run.regressionExperiment.id;details.append(link);root.append(details);} if(run.eligibilityContract){const details=el("details");details.append(el("summary","Authority and policy: "+run.eligibilityContract.fields.handoffAuthority),el("pre",run.eligibilityContract.agentInstructions));const link=el("a","Back to policy eligibility evidence →");link.href="/eligibility.html";details.append(link);root.append(details);} if(run.authorityContract){const details=el("details");details.append(el("summary","Operator authority: "+run.authorityContract.fields.handoffAuthority),el("pre",run.authorityContract.agentInstructions));const link=el("a","Back to authority experiment →");link.href="/authority.html?experiment="+run.authorityExperiment.id;details.append(link);root.append(details);} if(run.contract){const brief=el('details');brief.append(el('summary',`Shared task contract v${run.contract.version} · ${run.contract.brief.fields.name}`),el('p',run.contract.brief.fields.purpose),el('p',run.contract.hash,'meta'),el('pre',run.contract.agentInstructions));const link=el('a','Agent brief and contract comparison');link.href='/brief.html';brief.append(link);root.append(brief);}
 if(run.mode==='codex')root.append(el('p',`Requested model: ${run.agent.model||'unreported'} · Provider snapshot: ${run.agent.execution?.providerReportedModel||'not reported'}`,'meta'));
 if(run.evaluation?.outcome==='fail')root.append(el('p','Task checks failed. A passing AI reply review does not override a failed action or structured-field check.','task-failure'));
 if(run.experiment){const query=new URL(location.href).searchParams,comparison=query.get('run')===run.id?query.get('comparison'):null;const link=el('a',run.contract?'Back to brief comparison →':'Back to experiment →');link.href=run.contract?'/brief.html'+(comparison?'?comparison='+encodeURIComponent(comparison):''):'/compare.html?experiment='+run.experiment.id;root.append(link);}
 const actions=el('div',undefined,'actions');const ex=el('button','View export','secondary');ex.onclick=()=>{let area=$('#run-export');if(!area){const label=el('label','Run JSON · select and copy');label.htmlFor='run-export';area=el('textarea');area.id='run-export';area.readOnly=true;root.append(label,area);}area.value=JSON.stringify(currentRun,null,2);area.focus();area.select();};actions.append(ex);
 if(run.status==='completed'){if((run.contract&&run.experiment)||run.authorityExperiment||run.eligibilityExperiment||run.regressionExperiment||run.clarificationExperiment||run.continuationBatch)root.append(el('p','This comparison retains its first scheduled AI review. Failed or missing reviews are not replaced; start a new comparison for another evaluation.','help'));const review=el('button','Review reply with AI','secondary');review.onclick=async()=>{review.disabled=true;const cancel=el('button','Cancel AI review','secondary');cancel.onclick=()=>api(`/api/runs/${run.id}/cancel`,{method:'POST'}).catch(e=>$('#notice').textContent=e.message);actions.append(cancel);$('#notice').textContent='Reviewing the reply against sources and trace. A new review uses Codex allowance and is bounded to 90 seconds; an existing matching review is reused.';try{await api(`/api/runs/${run.id}/review`,{method:'POST'});$('#notice').textContent='Review saved separately. Original grade preserved.';await openRun(run.id);}catch(e){$('#notice').textContent=e.message;}finally{review.disabled=false;cancel.remove();}};if((run.contract&&run.experiment)||run.authorityExperiment||run.eligibilityExperiment||run.regressionExperiment||run.clarificationExperiment||run.continuationBatch){review.textContent='First review retained';review.disabled=true;}actions.append(review);const again=el('button','Reassess saved output','secondary');again.onclick=async()=>{try{await api('/api/runs/'+run.id+'/reassess',{method:'POST'});await openRun(run.id);}catch(e){$('#notice').textContent=e.message;}};if(run.continuationBatch){again.disabled=true;again.textContent='Frozen continuation grade';}actions.append(again);}
 if(run.eligibilityExperiment&&['running','queued'].includes(run.status))root.append(el('p','This batch is owned by the command-line coordinator. Use Ctrl+C there to cancel remaining work.','help'));if(!run.eligibilityExperiment&&['running','queued'].includes(run.status)){const c=el('button','Cancel run','secondary');c.onclick=async()=>{try{await api(`/api/runs/${run.id}/cancel`,{method:'POST'});}catch(e){$('#notice').textContent=e.message;}};actions.append(c);}root.append(actions);
 root.append(el('p',`Elapsed: ${run.usage.elapsedMs===null?(['running','queued'].includes(run.status)?'running':'unavailable'):(run.usage.elapsedMs/1000).toFixed(1)+'s'} · Tokens: ${run.usage.tokens?JSON.stringify(run.usage.tokens):'unavailable'} · Monetary cost: unavailable`,'meta'));if(run.error)root.append(el('p',run.error));
 renderDiagnostics(root,run.executionDiagnostics);
 if(result){root.append(el('h3','Evaluation outcome'),badge(result.outcome),el('p',result.version+(run.assessments?.length?' · Reassessed saved output. Original result retained in export.':' · Original assessment'),'meta'));const grid=el('div',undefined,'criteria');for(const c of result.criteria){const box=el('article',undefined,'criterion');box.append(badge(c.outcome),el('h3',c.title),el('p',c.evidence),el('p',c.scope,'meta'));grid.append(box);}root.append(grid);}
 for(const review of run.reviews||[])renderReview(root,review);root.append(el('h3','Customer reply'),el('p',run.final?.reply||'No final reply yet.','reply'),el('h3','Execution trace'));const trace=el('ol',undefined,'trace');for(const e of run.trace){const item=el('li');item.append(el('strong',`${e.seq} · ${e.kind}${e.tool?' · '+e.tool:''}`),el('pre',JSON.stringify(e.action||e.result||e.message||e.error,null,2)));trace.append(item);}root.append(trace);
 const inputs=el('details');inputs.append(el('summary','Frozen inputs, source hashes and limits'),el('pre',JSON.stringify({scenario:run.scenario,scenarioHash:run.scenarioHash,sources:run.sources,agent:run.agent,limits:run.limits,evaluator:run.evaluation?.version,authorityContract:run.authorityContract,eligibilityContract:run.eligibilityContract,regressionContract:run.regressionContract,regressionCell:run.regressionCell,clarificationContract:run.clarificationContract,clarificationCell:run.clarificationCell,...(run.contract?{contract:run.contract}:{} )},null,2)));root.append(inputs);
}
async function openRun(id){selected=id;clearTimeout(poll);try{const run=await api(`/api/runs/${id}`);const key=JSON.stringify([run.id,run.status,run.trace.length,run.evaluation,run.assessments,run.reviews]);if(key!==renderKey){render(run);renderKey=key;}await refresh();if(['queued','running'].includes(run.status))poll=setTimeout(()=>openRun(id),1000);}catch(e){$('#notice').textContent=e.message;}}
$('#refresh').onclick=()=>refresh().catch(e=>$('#notice').textContent=e.message);
$('#run-form').onsubmit=async event=>{event.preventDefault();$('#notice').textContent='';$('#start').disabled=true;try{const run=await api('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:$('#scenario').value,mode:$('#mode').value,fixture:$('#fixture').value,configuration:$('#configuration').value})});await openRun(run.id);}catch(e){$('#notice').textContent=e.message;$('#start').disabled=false;}};
try{
 const config=await api('/api/config');scenarioOptions=config.scenarios;for(const s of scenarioOptions){const o=el('option',s.title);o.value=s.id;$('#scenario').append(o);}for(const c of config.configurations){const o=el('option',`${c.name} · v${c.version} · ${c.model}`);o.value=`${c.id}@${c.version}`;$('#configuration').append(o);}for(const [id,title]of Object.entries(config.fixtures)){const o=el('option',title);o.value=id;$('#fixture').append(o);}
 if(!config.codexAvailable){$('#mode option[value="codex"]').disabled=true;$('#mode-help').textContent+=' Codex CLI is unavailable on this host.';}$('#sources').append(el('p',config.scenario.ticket));for(const doc of config.scenario.documents){const a=el('article');a.append(el('h3',`${doc.id} · ${doc.title}`),el('p',doc.text));$('#sources').append(a);}setScenario();await refresh();const id=new URL(location.href).searchParams.get('run');if(id)await openRun(id);
 if(selected)$('#detail').scrollIntoView({block:'start'});
}catch(e){$('#notice').textContent=`Could not load the lab: ${e.message}. Start the local server and refresh.`;}
