import {esc, pretty, runEvidence} from './workflow-view.js';

// Presentation of verified saved records only. Never execute or regrade here.
export function renderPublicDemo({report, seal}, {staticSite = false} = {}) {
  const row = report.rows.find(row => row.runId === '893fc772-4000-4212-84f4-990703a98e4d');
  if (!row || row.outcome !== 'fail') throw Error('The retained example is unavailable');
  const run = row.run;
  const results = run.trace.filter(event => event.kind === 'tool_result');
  const documents = new Set(run.scenario.documents.map(doc => doc.id));
  const check = run.evaluation.criteria.find(check => check.id === 'sources');
  const source = staticSite ? 'report.json' : '/api/workflow/continuation';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A convincing agent reply still failed. Inspect the saved reply, actual simulated actions and original requirement in Taskwright."><title>A good reply. A failed requirement. · Taskwright</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="lab.css"><link rel="stylesheet" href="workflow.css"><link rel="stylesheet" href="public-demo.css"></head>
  <body class="demo-page"><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="${staticSite ? './' : '/demo.html'}">Taskwright</a><nav aria-label="Demo navigation"><a href="#story">The example</a><a href="#failure">Why it failed</a><a href="#evidence">Full evidence</a><a href="https://github.com/robertbradley-oss/taskwright">GitHub ↗</a></nav></header>
  <main id="main" tabindex="-1"><section class="demo-hero"><div class="eyebrow">AGENT EVALUATION · SAVED MODEL EVIDENCE</div><h1>A good reply.<br>A failed requirement.</h1><p class="lead">The agent read the right documents and opened the right handoff. Its AI reply review passed. So why did this attempt fail?</p><a class="button-link" href="#story">Inspect the example ↓</a><p class="help">Fictional support data. Recorded model execution with simulated tools. Viewing this page makes no model calls.</p></section>
  <section id="story" class="demo-section"><div class="eyebrow">01 · THE CUSTOMER AND THE REPLY</div><h2>Would you accept this answer?</h2><div class="evidence-columns"><article><h3>The customer's situation</h3><p>Morgan's Vale S6 USB still will not feed paper after all three required troubleshooting steps. Morgan asks the agent to proceed with specialist review.</p><details><summary>Read the exact supplied conversation</summary><blockquote>${esc(run.scenario.ticket)}</blockquote></details><h3>The requirement</h3><p>Read the product and policy documents before acting. Once the steps have failed, open exactly one simulated handoff. Cite document IDs in <code>evidence_ids</code>.</p><details><summary>Inspect the frozen contract</summary><pre>${pretty(report.plan.contract)}</pre></details></article><article><h3>The actual agent reply</h3><blockquote class="reply">${esc(run.final.reply)}</blockquote><p>First AI reply review: <strong>${esc(row.review.evaluation.outcome)}</strong>. That judgment is separate from the contract checks.</p></article></div><a href="#actions">Check what it actually did ↓</a></section>
  <section id="actions" class="demo-section"><div class="eyebrow">02 · RECORDED ACTIONS</div><h2>The handoff really happened—in the simulation.</h2><p>These are successful tool results from this recorded turn, in order. Open an event to inspect its original payload.</p><ol class="demo-actions">${results.map(event => `<li><details><summary>Event ${esc(event.seq)} · ${event.tool === 'read_document' ? `Read ${esc(event.result.id)} document` : 'Recorded the simulated handoff'} · ${event.ok ? 'succeeded' : 'failed'}</summary><pre>${pretty(event)}</pre></details></li>`).join('')}</ol><a href="#failure">Reveal the failed requirement ↓</a></section>
  <section id="failure" class="demo-section"><div class="eyebrow">03 · THE EXACT MISMATCH</div><h2>A receipt is not a source document.</h2><p>The agent returned these values in <code>evidence_ids</code>. The first two identify documents. The last identifies the completed action.</p><ul class="citation-list">${run.final.evidence_ids.map(id => `<li><code>${esc(id)}</code><strong>${documents.has(id) ? 'Document ID · valid' : 'Handoff receipt · invalid in this field'}</strong></li>`).join('')}</ul><details><summary>Original failed check · ${esc(check.title)}</summary><p>${esc(check.evidence)}</p></details><h3>Why this matters</h3><p>A system consuming a document-only citation field needs references it can resolve to source text. A real action receipt proves an action happened; it does not identify a supporting document. Here, the check caught that mismatch even though the reply sounded right.</p><p>This also exposes ambiguity in the output interface. Clarifying how receipts should be returned would require a new contract and a new test—not changing this grade.</p><div class="demo-result"><strong>9/12 full-contract passes</strong><p>All 12 handoff decisions and first AI reply reviews passed. Three attempts retained this citation failure. The original decision remains <code>${esc(report.decision)}</code>.</p></div></section>
  <section id="evidence" class="demo-section"><div class="eyebrow">04 · VERIFY THE STORY</div><h2>Every claim leads back to a record.</h2><details><summary>Inspect this attempt's full evidence</summary>${runEvidence(row)}</details><details><summary>All 12 original outcomes</summary><div class="table-wrap"><table><thead><tr><th>Attempt</th><th>Authority</th><th>History</th><th>Full contract</th><th>AI review</th></tr></thead><tbody>${report.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.mode)}</td><td>${esc(r.history)}</td><td>${esc(r.outcome)}</td><td>${esc(r.review?.evaluation?.outcome)}</td></tr>`).join('')}</tbody></table></div></details><a href="${source}" download>Download the complete saved ${staticSite ? 'report' : 'evidence package'}</a><details><summary>Seal identity and interpretation limits</summary><pre>${pretty(seal)}</pre><p>The build checks the report against its recorded seal. This establishes consistency, not independent authenticity. These are fresh second turns with reconstructed prior context and scripted customer follow-ups, not 12 independent full dialogues. The same model family produced replies and reviews. This small exposed fictional suite does not establish production reliability. Four reserved cases remain unexecuted.</p></details><p>Saved evidence is previously executed model work. Offline replay executes scripted fixtures. Fresh execution invokes a model. This demonstration only presents saved evidence.</p>${staticSite ? '<p>To explore configuration comparisons and local execution, follow the setup instructions in the repository.</p>' : '<a class="button-link secondary" href="/#brief">Explore the saved comparison →</a>'}</section></main><footer>Read-only demonstration · Fictional customers and tools · Original grades preserved · <a href="https://github.com/robertbradley-oss/taskwright">Source and local setup</a></footer></body></html>`;
}
