const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={checks_pass:'Checks pass',task_fail:'Task failed',reply_fail:'Reply failed',both_fail:'Both layers failed',uncertain:'Uncertain',execution_error:'Execution error',pending:'Pending',invalid_evidence:'Evidence mismatch'};
const badge=outcome=>`<span class="badge ${outcome==='checks_pass'?'pass':['task_fail','reply_fail','both_fail','invalid_evidence','execution_error'].includes(outcome)?'fail':'uncertain'}">${escape(labels[outcome]||outcome)}</span>`;
const summaryLabels={checks_pass:'checks pass',task_fail:'task failures',reply_fail:'reply failures',both_fail:'failures in both layers',uncertain:'uncertain',execution_error:'execution errors',pending:'pending',invalid_evidence:'evidence mismatches'};
const tally=counts=>Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`${n} ${summaryLabels[k]}`).join(' · ');
function scenarioEvidence(data,s){
 const selected=data.rows.filter(r=>r.scenario===s.id);
 const count=(arm,id)=>selected.filter(r=>r.arm===arm&&(id==='reply'?r.review?.status==='completed'&&r.reply==='pass':r.run?.evaluation?.criteria.some(c=>c.id===id&&c.outcome==='pass'))).length;
 return `<div class="suite-checks" role="table" aria-label="${escape(s.title)} checks passed"><div role="row"><span role="columnheader">Check passed</span><span role="columnheader">Baseline</span><span role="columnheader">Candidate</span></div>${[['model','Model / connection'],['policy','Declared commitment'],['sources','Required sources'],['handoff','Handoff rule'],['reply','AI reply review']].map(([id,title])=>`<div role="row"><span role="rowheader">${title}</span><span role="cell">${count('baseline',id)} / 2</span><span role="cell">${count('candidate',id)} / 2</span></div>`).join('')}</div>`;
}
let report;
function render(data){
 report=data;const p=data.plan;
 $('notice').textContent=`Updated ${new Date(data.updatedAt).toLocaleString()}. ${data.rows.filter(r=>r.review).length} of 16 reply reviews recorded.`;
 const decisionTitle={blocked:'Selection blocked',pending:'Comparison in progress',candidate_selected:'Candidate selected for reserved evaluation',not_selected:'Candidate not selected'};
 $('decision').innerHTML=`<div class="${data.decision.status==='blocked'?'task-failure':'verdict'}"><strong>${escape(decisionTitle[data.decision.status])}</strong><p>${escape(data.decision.text)}</p>${data.issues.length?`<ul>${data.issues.map(i=>`<li>${escape(i)}</li>`).join('')}</ul>`:''}</div>`;
 $('metrics').innerHTML=['baseline','candidate'].map(arm=>{const a=data.arms[arm],u=a.usage;return `<article class="metric-card"><h3>${escape(p.arms[arm].name)} · v${p.arms[arm].version}</h3><p class="big-number">${a.counts.checks_pass} / ${a.scheduled} checks pass</p><p>${escape(tally(a.counts))}</p><p>Support: ${u.support.input.toLocaleString()} input / ${u.support.output.toLocaleString()} output tokens (${u.support.known}/${a.scheduled} known).</p><p>Reviews: ${u.review.input.toLocaleString()} input / ${u.review.output.toLocaleString()} output tokens (${u.review.known}/${a.scheduled} known).</p><p>Elapsed support / review: ${(u.supportElapsedMs/1000).toFixed(1)}s / ${(u.reviewElapsedMs/1000).toFixed(1)}s. Monetary cost unavailable.</p></article>`;}).join('');
 $('reservation').textContent=`Reserved ${new Date(p.reservation.reservedAt).toLocaleString()}, before candidate v${p.arms.candidate.version} was created. ${p.reservation.count} cases remain unexecuted by this runner. Their content hash is ${p.reservation.casesHash}.`;
 $('breakdown').innerHTML=data.scenarios.map(s=>`<article class="criterion"><h3>${escape(s.title)}</h3><p><strong>Baseline:</strong> ${escape(tally(s.arms.baseline))}</p><p><strong>Candidate:</strong> ${escape(tally(s.arms.candidate))}</p>${scenarioEvidence(data,s)}</article>`).join('');
 $('controls').innerHTML=`<h3>Predeclared selection rule</h3><p>${escape(p.decision.rule)}</p><p>${escape(p.order)}</p>${['baseline','candidate'].map(arm=>`<h3>${escape(p.arms[arm].name)} v${p.arms[arm].version}</h3><p>${escape(p.arms[arm].instructions)}</p><p class="meta">Configuration hash: ${escape(p.arms[arm].hash)}</p>`).join('')}<pre>${escape(JSON.stringify(p.controls,null,2))}</pre><p class="meta">Plan hash: ${escape(p.hash)}</p><p class="help">The requested model alias and CLI version are fixed. The provider's exact model snapshot is not reported. Cached input is included in input totals, not added again.</p>`;
 $('trials').innerHTML=data.rows.map((r,i)=>{const failures=r.run?.evaluation?.criteria.filter(c=>c.outcome==='fail')||[],replyFailures=r.review?.evaluation?.criteria.filter(c=>c.outcome!=='pass')||[];return `<article class="trial"><strong>${i+1}. ${escape(r.title)}</strong>${badge(r.outcome)}<small>${escape(r.arm)} · trial ${r.repetition} · execution ${escape(r.run?.status||'not started')} · structural ${escape(r.run?.evaluation?.outcome||'pending')} · AI reply ${escape(r.reply||'pending')}</small>${failures.map(c=>`<p class="issue">Task: ${escape(c.title)} — ${escape(c.evidence||c.reason||c.outcome)}</p>`).join('')}${replyFailures.map(c=>`<p class="issue">Reply: ${escape(c.title)} — ${escape(c.reason)}</p>`).join('')}${r.review?.error?`<p class="issue">Review error: ${escape(r.review.error)}</p>`:''}${r.runId?`<a href="/?run=${encodeURIComponent(r.runId)}">Inspect original run →</a><details><summary>Reply and retained review evidence</summary><p class="reply">${escape(r.run?.final?.reply||'No final reply')}</p><pre>${escape(JSON.stringify({structural:r.run?.evaluation,review:r.review},null,2))}</pre></details>`:''}</article>`;}).join('');
}
async function refresh(){try{const res=await fetch('/api/suite');if(!res.ok)throw Error('Suite evidence is not available.');render(await res.json());}catch(e){$('notice').textContent=e.message;}}
$('refresh').addEventListener('click',refresh);
$('export').addEventListener('click',()=>{if(!report)return;$('export-panel').hidden=false;$('suite-export').value=JSON.stringify(report,null,2);$('suite-export').focus();$('suite-export').select();$('notice').textContent='Complete suite JSON is ready to select and copy. No model call was made.';});
await refresh();
