export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const pretty = value => esc(JSON.stringify(value, null, 2));
export const badge = value => `<span class="badge ${value === 'pass' ? 'pass' : ['fail','execution_error','invalid_evidence'].includes(value) ? 'fail' : 'uncertain'}">${esc(value || 'pending')}</span>`;
export const decisionTitles = {tie:'Both qualify. No advantage established.',candidate_qualifies:'Candidate qualifies under this contract.',baseline_qualifies:'Baseline qualifies under this contract.',neither_qualifies:'Neither configuration qualifies.',incomplete:'Incomplete evidence. No selection.',blocked:'Evidence mismatch. Selection blocked.',inconclusive:'Uncertain judgments. No preference.',running:'Comparison in progress.'};
export function rowLabel(row) { return `${row.run?.scenario?.title || row.scenario} · ${row.arm || row.mode} · trial ${row.repetition ?? row.trial} · ${row.outcome}`; }
export function grades(row) {
  return `<div class="grade-strip"><span>Full contract ${badge(row.outcome)}</span>${['advice','actions','process'].map(key => `<span>${key[0].toUpperCase()+key.slice(1)} ${badge(row[key])}</span>`).join('')}</div>`;
}
export function runEvidence(row) {
  const run = row.run, review = row.review;
  if (!run) return '<p class="verdict">This scheduled attempt has no saved run record. It remains in the denominator.</p>';
  return `${grades(row)}<p class="meta">Run ${esc(row.runId)} · ${esc(run.status)} · originally ${esc(run.mode)} · ${esc(run.createdAt)}</p>
  ${run.error ? `<p class="issue">Execution error: ${esc(run.error)}</p>` : ''}
  <div class="evidence-columns"><div><h3>Customer ticket</h3><blockquote>${esc(run.scenario.ticket)}</blockquote>
  ${run.continuation ? `<details><summary>Conversation and supplied follow-up history</summary><pre>${pretty(run.continuation)}</pre></details>` : ''}
  <h3>Frozen source documents</h3>${run.scenario.documents.map(doc => `<details><summary>${esc(doc.title)} · ${esc(doc.id)}</summary><p>${esc(doc.text)}</p><p class="meta">Document version ${esc(doc.version)}</p></details>`).join('')}
  <h3>Ordered execution trace</h3><ol class="trace">${run.trace.map(event => `<li><details><summary>Event ${esc(event.seq)} · ${esc(event.kind)}${event.tool || event.action?.tool ? ' · '+esc(event.tool || event.action.tool) : ''}</summary><pre>${pretty(event)}</pre></details></li>`).join('') || '<li>No events recorded.</li>'}</ol></div>
  <div><h3>Actual customer reply</h3><div class="reply">${esc(run.final?.reply || 'No final reply was recorded.')}</div><details><summary>Structured output fields</summary><pre>${pretty(run.final)}</pre></details>
  <h3>Original task checks</h3><p class="help">These inspect fields, source reads and actions. The original prose check can remain uncertain even when a separate AI review passes.</p>
  ${run.evaluation?.criteria.map(check => `<details${check.outcome==='fail'?' open':''}><summary>${badge(check.outcome)} ${esc(check.title)}</summary><p>${esc(check.evidence)}</p><p class="meta">Requirement: ${esc(check.requirementId || 'See original task contract')}</p></details>`).join('') || '<p>No original grade recorded.</p>'}
  <section class="semantic-review"><h3>First AI reply review ${badge(review?.evaluation?.outcome)}</h3><p class="help">A separate model judgment, preserved as recorded. It cannot override a failed action or required process.</p>
  ${review?.evaluation?.criteria.map(check => `<details class="review-criterion"><summary>${badge(check.outcome)} ${esc(check.title || check.id)}</summary><h4>Claim checked</h4><blockquote>${esc(check.claim)}</blockquote><p>${esc(check.reason)}</p>${check.evidence.map(e => `<p class="meta">${esc(e.source_id)}</p><blockquote>${esc(e.quote)}</blockquote>`).join('')}</details>`).join('') || `<p>${esc(review?.error || 'No completed first review available.')}</p>`}
  <p class="meta">Reviewer version ${esc(review?.version || 'unavailable')} · status ${esc(review?.status || 'missing')}</p></section></div></div>
  <details><summary>Execution controls, usage and provenance</summary><pre>${pretty({agent:run.agent,limits:run.limits,usage:run.usage,sources:run.sources,scenarioHash:run.scenarioHash,contractHash:run.contractHash,reviewHash:review?.originalHash})}</pre></details>`;
}
export function renderStage(step, report, selected, metadata) {
  const {plan, rows} = report, contract = plan.contract;
  const head = (number,title,lead) => `<div class="eyebrow">${number} / 05</div><h2 id="stage-title" tabindex="-1">${title}</h2><p class="stage-lead">${lead}</p>`;
  if (step === 'brief') return `${head('01','Start with an explicit brief.','These are the frozen requirements that both configurations received. Review what counts before looking at the scores.')}<p class="brief-purpose">${esc(contract.brief.fields.purpose)}</p><p class="meta">${esc(contract.brief.fields.name)} · frozen contract v${esc(contract.version)}</p><div class="criteria">${contract.requirements.map(r => `<article class="criterion"><span class="badge">${esc(r.category)}</span><h3>${esc(r.requirement)}</h3><p><strong>Why:</strong> ${esc(r.why)}</p><p><strong>Evidence:</strong> ${esc(r.evidence)}</p><details><summary>Requirement-to-grader mapping</summary><p class="meta">${esc(r.id)} → task checks: ${esc(r.structural.join(', ') || 'none')}; AI review: ${esc(r.semantic.join(', ') || 'none')}</p></details></article>`).join('')}</div><details><summary>Exact shared instructions and contract identity</summary><pre>${esc(contract.agentInstructions)}</pre><p class="meta">${esc(contract.hash)}</p><p>${esc(contract.limitsNote)}</p></details><a class="button-link secondary" href="/brief.html?from=workflow">Create your own brief →</a><p class="help">The editor supports purpose and evidence-process changes. Arbitrary purpose text does not generate new graders. Handoff-authority controls have their own workbench in the evidence library.</p>`;
  if (step === 'run') return `${head('02','Keep the test conditions fixed.','Inspect the saved schedule, then choose an attempt to follow. Nothing on this page launches a new agent.')}<div class="verdict"><strong>${rows.length} scheduled attempts · ${rows.filter(r=>r.run?.status==='completed').length} completed replies · ${rows.filter(r=>r.review?.status==='completed').length} completed first reviews</strong><p>Two configurations receive the same brief, tools and sources. ${esc(plan.repetitions)} trials per configuration on each of ${contract.scenarios.length} development tasks.</p><p>${esc(plan.selectionRule)}</p></div><div class="metric-grid">${['baseline','candidate'].map(arm=>`<article class="metric-card"><span class="eyebrow">${arm}</span><h3>${esc(plan.arms[arm].name)} v${esc(plan.arms[arm].version)}</h3><details><summary>Strategy instructions and controls</summary><pre>${pretty(plan.arms[arm])}</pre></details></article>`).join('')}</div><label for="attempt">Saved attempt to inspect</label><select id="attempt">${rows.map(r=>`<option value="${esc(r.runId)}"${r.runId===selected?' selected':''}>${esc(rowLabel(r))}</option>`).join('')}</select><div class="actions"><a class="button-link" href="#evidence">Inspect this attempt →</a><a class="button-link secondary" href="/brief.html?from=workflow#comparison-title">Set up a fresh comparison</a></div><p class="help">Fresh comparisons use signed-in Codex allowance, with bounded attempts and reviews. The setup screen shows prerequisites and limits before launch. Saved results need no credentials.</p><details><summary>Exact frozen schedule and review controls</summary><pre>${pretty({experiments:plan.experiments.map(e=>({id:e.id,schedule:e.schedule})),reviewControls:plan.reviewControls})}</pre></details>`;
  if (step === 'evidence') return `${head('03','Connect the reply to its evidence.','Inspect the original task checks and first AI review separately. Open a source or trace event to check what actually happened.')}<label for="attempt">Saved attempt</label><select id="attempt">${rows.map(r=>`<option value="${esc(r.runId)}"${r.runId===selected?' selected':''}>${esc(rowLabel(r))}</option>`).join('')}</select>${runEvidence(rows.find(r=>r.runId===selected)||rows[0])}`;
  if (step === 'compare') return `${head('04',esc(decisionTitles[report.decision] || report.decision),'Every scheduled attempt counts. A fluent reply does not excuse an unauthorized action or missing required evidence.')}<div class="verdict"><p>${esc(plan.selectionRule)}</p><p>${esc(report.limits)}</p>${report.active?'<p><strong>Provisional: this comparison is still running.</strong></p>':''}${report.issues.length?`<p class="issue">${esc(report.issues.join('; '))}</p>`:''}</div><div class="metric-grid">${['baseline','candidate'].map(arm=>{const a=report.arms[arm];return `<article class="metric-card"><h3>${esc(plan.arms[arm].name)} v${esc(plan.arms[arm].version)}</h3><p class="big-number">${a.overall.pass} / ${a.scheduled}</p><p>Full-contract passes</p><p>Advice ${a.advice.pass}/${a.scheduled} · Actions ${a.actions.pass}/${a.scheduled} · Process ${a.process.pass}/${a.scheduled}</p><p>Monetary cost: unavailable</p></article>`;}).join('')}</div><div class="table-scroll"><table><caption>All attempts under this contract</caption><thead><tr><th scope="col">Task / configuration</th><th scope="col">Advice / actions / process</th><th scope="col">Full contract</th><th scope="col">Evidence</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${esc(r.run?.scenario.title||r.scenario)}<br><span class="meta">${esc(r.arm)} · trial ${r.repetition}</span></th><td>${esc(r.advice)} / ${esc(r.actions)} / ${esc(r.process)}</td><td>${badge(r.outcome)}</td><td><button class="secondary" data-run="${esc(r.runId)}" aria-label="Inspect ${esc(rowLabel(r))}">Inspect</button></td></tr>`).join('')}</tbody></table></div><p>Results describe these exposed development tasks. They do not establish production reliability, model learning or success on the four reserved cases.</p>`;
  return `${head('05','Take the evidence with you.','Export the complete comparison, including the frozen brief, both configurations, every run, and each retained first review.')}<p>Report identity: <span class="meta">${esc(plan.id)}</span></p><p>${esc(metadata.seal ? 'The saved report matches its recorded seal. Exporting does not regrade or rerun it.' : 'This is a snapshot of a local comparison. It is not the sealed worked example.')}</p>${report.active?'<p class="verdict">This export is provisional because the comparison is still running. Refresh results after execution completes.</p>':''}<div class="actions"><button id="download-report">Download comparison JSON</button><button id="show-json" class="secondary">View copyable JSON</button></div><p id="export-status" role="status"></p><div id="copy-panel" hidden><label for="export-text">Complete comparison JSON</label><textarea class="raw-export" id="export-text" readonly spellcheck="false"></textarea></div><details><summary>Provenance and interpretation limits</summary><pre>${pretty({source:metadata.source,seal:metadata.seal,planHash:plan.hash,contractHash:contract.hash})}</pre><p>${esc(report.limits)}</p><p>References were authored and reviewed with AI assistance; they are not independent human ground truth. Frozen historical names remain unchanged.</p></details><div class="actions"><a class="button-link secondary" href="/brief.html?from=workflow">Create your own brief →</a><a href="#library">Explore a retained failure</a></div>`;
}
